"""Jira Data Center REST API endpoint definitions.

Auto-generated scaffold from the OpenAPI spec. Safe to hand-edit.
"""

from __future__ import annotations

from atlassian.core.endpoint import Endpoint

# --- Agile ---

MOVE_ISSUES_TO_BACKLOG = Endpoint("POST", "/agile/1.0/backlog/issue", "Update issues to move them to the backlog")
GET_ALL_BOARDS = Endpoint("GET", "/agile/1.0/board", "Get all boards")
CREATE_BOARD = Endpoint("POST", "/agile/1.0/board", "Create a new board")
DELETE_BOARD = Endpoint("DELETE", "/agile/1.0/board/{boardId}", "Delete the board")
GET_BOARD = Endpoint("GET", "/agile/1.0/board/{boardId}", "Get a single board")
GET_ISSUES_FOR_BACKLOG = Endpoint("GET", "/agile/1.0/board/{boardId}/backlog", "Get all issues from the board's bac...")
GET_CONFIGURATION = Endpoint("GET", "/agile/1.0/board/{boardId}/configuration", "Get the board configuration")
GET_EPICS = Endpoint("GET", "/agile/1.0/board/{boardId}/epic", "Get all epics from the board")
GET_ISSUES_WITHOUT_EPIC = Endpoint("GET", "/agile/1.0/board/{boardId}/epic/none/issue", "Get all issues without an ...")
GET_ISSUES_FOR_EPIC = Endpoint("GET", "/agile/1.0/board/{boardId}/epic/{epicId}/issue", "Get all issues for a speci...")
GET_ISSUES_FOR_BOARD = Endpoint("GET", "/agile/1.0/board/{boardId}/issue", "Get all issues from a board")
GET_PROJECTS = Endpoint("GET", "/agile/1.0/board/{boardId}/project", "Get all projects associated with the board")
GET_PROPERTIES_KEYS = Endpoint("GET", "/agile/1.0/board/{boardId}/properties", "Get all properties keys for a board")
DELETE_PROPERTY = Endpoint("DELETE", "/agile/1.0/board/{boardId}/properties/{propertyKey}", "Delete a property from...")
GET_PROPERTY = Endpoint("GET", "/agile/1.0/board/{boardId}/properties/{propertyKey}", "Get a property from a board")
SET_PROPERTY = Endpoint("PUT", "/agile/1.0/board/{boardId}/properties/{propertyKey}", "Update a board's property")
GET_REFINED_VELOCITY = Endpoint("GET", "/agile/1.0/board/{boardId}/settings/refined-velocity", "Get the value of th...")
SET_REFINED_VELOCITY = Endpoint("PUT", "/agile/1.0/board/{boardId}/settings/refined-velocity", "Update the board's ...")
GET_ALL_SPRINTS = Endpoint("GET", "/agile/1.0/board/{boardId}/sprint", "Get all sprints from a board")
GET_ISSUES_FOR_SPRINT = Endpoint("GET", "/agile/1.0/board/{boardId}/sprint/{sprintId}/issue", "Get all issues for a...")
GET_ALL_VERSIONS = Endpoint("GET", "/agile/1.0/board/{boardId}/version", "Get all versions from a board")
GET_ISSUES_WITHOUT_EPIC_1 = Endpoint("GET", "/agile/1.0/epic/none/issue", "Get issues without an epic")
REMOVE_ISSUES_FROM_EPIC = Endpoint("POST", "/agile/1.0/epic/none/issue", "Remove issues from any epic")
GET_EPIC = Endpoint("GET", "/agile/1.0/epic/{epicIdOrKey}", "Get an epic by id or key")
PARTIALLY_UPDATE_EPIC = Endpoint("POST", "/agile/1.0/epic/{epicIdOrKey}", "Update an epic's details")
GET_ISSUES_FOR_EPIC_1 = Endpoint("GET", "/agile/1.0/epic/{epicIdOrKey}/issue", "Get issues for a specific epic")
MOVE_ISSUES_TO_EPIC = Endpoint("POST", "/agile/1.0/epic/{epicIdOrKey}/issue", "Move issues to a specific epic")
RANK_EPICS = Endpoint("PUT", "/agile/1.0/epic/{epicIdOrKey}/rank", "Rank an epic relative to another")
CREATE_SPRINT = Endpoint("POST", "/agile/1.0/sprint", "Create a future sprint")
UNMAP_SPRINTS = Endpoint("PUT", "/agile/1.0/sprint/unmap", "Unmap sprints from being synced")
UNMAP_ALL_SPRINTS = Endpoint("PUT", "/agile/1.0/sprint/unmap-all", "Unmap all sprints from being synced")
DELETE_SPRINT = Endpoint("DELETE", "/agile/1.0/sprint/{sprintId}", "Delete a sprint")
GET_SPRINT = Endpoint("GET", "/agile/1.0/sprint/{sprintId}", "Get sprint by id")
PARTIALLY_UPDATE_SPRINT = Endpoint("POST", "/agile/1.0/sprint/{sprintId}", "Partially update a sprint")
UPDATE_SPRINT = Endpoint("PUT", "/agile/1.0/sprint/{sprintId}", "Update a sprint fully")
GET_ISSUES_FOR_SPRINT_1 = Endpoint("GET", "/agile/1.0/sprint/{sprintId}/issue", "Get all issues in a sprint")
MOVE_ISSUES_TO_SPRINT = Endpoint("POST", "/agile/1.0/sprint/{sprintId}/issue", "Move issues to a sprint")
GET_PROPERTIES_KEYS_1 = Endpoint("GET", "/agile/1.0/sprint/{sprintId}/properties", "Get all properties keys for a s...")
DELETE_PROPERTY_1 = Endpoint("DELETE", "/agile/1.0/sprint/{sprintId}/properties/{propertyKey}", "Delete a sprint's ...")
GET_PROPERTY_1 = Endpoint("GET", "/agile/1.0/sprint/{sprintId}/properties/{propertyKey}", "Get a property for a sprint")
SET_PROPERTY_1 = Endpoint("PUT", "/agile/1.0/sprint/{sprintId}/properties/{propertyKey}", "Update a sprint's property")
SWAP_SPRINT = Endpoint("POST", "/agile/1.0/sprint/{sprintId}/swap", "Swap the position of two sprints")

# --- Project ---

CREATE_COMPONENT = Endpoint("POST", "/api/2/component", "Create component")
GET_PAGINATED_COMPONENTS = Endpoint("GET", "/api/2/component/page", "Get paginated components")
DELETE = Endpoint("DELETE", "/api/2/component/{id}", "Delete a project component")
GET_COMPONENT = Endpoint("GET", "/api/2/component/{id}", "Get project component")
UPDATE_COMPONENT = Endpoint("PUT", "/api/2/component/{id}", "Update a component")
GET_COMPONENT_RELATED_ISSUES = Endpoint("GET", "/api/2/component/{id}/relatedIssueCounts", "Get component related i...")
GET_ALL_PROJECTS = Endpoint("GET", "/api/2/project", "Get all visible projects")
CREATE_PROJECT = Endpoint("POST", "/api/2/project", "Create a new project")
GET_ALL_PROJECT_TYPES = Endpoint("GET", "/api/2/project/type", "Get all project types")
GET_PROJECT_TYPE_BY_KEY = Endpoint("GET", "/api/2/project/type/{projectTypeKey}", "Get project type by key")
GET_ACCESSIBLE_PROJECT_TYPE_BY_KEY = Endpoint("GET", "/api/2/project/type/{projectTypeKey}/accessible", "Get projec...")
DELETE_PROJECT = Endpoint("DELETE", "/api/2/project/{projectIdOrKey}", "Delete a project")
GET_PROJECT = Endpoint("GET", "/api/2/project/{projectIdOrKey}", "Get a project by ID or key")
UPDATE_PROJECT = Endpoint("PUT", "/api/2/project/{projectIdOrKey}", "Update a project")
ARCHIVE_PROJECT = Endpoint("PUT", "/api/2/project/{projectIdOrKey}/archive", "Archive a project")
CREATE_AVATAR_FROM_TEMPORARY_2 = Endpoint("POST", "/api/2/project/{projectIdOrKey}/avatar", "Create avatar from tem...")
UPDATE_PROJECT_AVATAR = Endpoint("PUT", "/api/2/project/{projectIdOrKey}/avatar", "Update project avatar")
STORE_TEMPORARY_AVATAR_USING_MULTI_PART_1 = Endpoint("POST", "/api/2/project/{projectIdOrKey}/avatar/temporary", "S...")
DELETE_AVATAR = Endpoint("DELETE", "/api/2/project/{projectIdOrKey}/avatar/{id}", "Delete an avatar")
GET_ALL_AVATARS = Endpoint("GET", "/api/2/project/{projectIdOrKey}/avatars", "Get all avatars for a project")
GET_PROJECT_COMPONENTS = Endpoint("GET", "/api/2/project/{projectIdOrKey}/components", "Get project components")
GET_PROPERTIES_KEYS_3 = Endpoint("GET", "/api/2/project/{projectIdOrKey}/properties", "Get keys of all properties f...")
DELETE_PROPERTY_5 = Endpoint("DELETE", "/api/2/project/{projectIdOrKey}/properties/{propertyKey}", "Delete property...")
GET_PROPERTY_5 = Endpoint("GET", "/api/2/project/{projectIdOrKey}/properties/{propertyKey}", "Get value of property...")
SET_PROPERTY_4 = Endpoint("PUT", "/api/2/project/{projectIdOrKey}/properties/{propertyKey}", "Set value of specifie...")
RESTORE_PROJECT = Endpoint("PUT", "/api/2/project/{projectIdOrKey}/restore", "Restore an archived project")
GET_PROJECT_ROLES = Endpoint("GET", "/api/2/project/{projectIdOrKey}/role", "Get all roles in project")
DELETE_ACTOR = Endpoint("DELETE", "/api/2/project/{projectIdOrKey}/role/{id}", "Delete actors from project role")
GET_PROJECT_ROLE = Endpoint("GET", "/api/2/project/{projectIdOrKey}/role/{id}", "Get details for a project role")
ADD_ACTOR_USERS = Endpoint("POST", "/api/2/project/{projectIdOrKey}/role/{id}", "Add actor to project role")
SET_ACTORS = Endpoint("PUT", "/api/2/project/{projectIdOrKey}/role/{id}", "Update project role with actors")
GET_ALL_STATUSES = Endpoint("GET", "/api/2/project/{projectIdOrKey}/statuses", "Get all issue types with statuses f...")
UPDATE_PROJECT_TYPE = Endpoint("PUT", "/api/2/project/{projectIdOrKey}/type/{newProjectTypeKey}", "Update project type")
GET_PROJECT_VERSIONS_PAGINATED = Endpoint("GET", "/api/2/project/{projectIdOrKey}/version", "Get paginated project ...")
GET_PROJECT_VERSIONS = Endpoint("GET", "/api/2/project/{projectIdOrKey}/versions", "Get project versions")
GET_ISSUE_SECURITY_SCHEME_1 = Endpoint("GET", "/api/2/project/{projectKeyOrId}/issuesecuritylevelscheme", "Get issu...")
GET_NOTIFICATION_SCHEME_1 = Endpoint("GET", "/api/2/project/{projectKeyOrId}/notificationscheme", "Get notification...")
GET_ASSIGNED_PERMISSION_SCHEME = Endpoint("GET", "/api/2/project/{projectKeyOrId}/permissionscheme", "Get assigned ...")
ASSIGN_PERMISSION_SCHEME = Endpoint("PUT", "/api/2/project/{projectKeyOrId}/permissionscheme", "Assign permission s...")
GET_ASSIGNED_PRIORITY_SCHEME = Endpoint("GET", "/api/2/project/{projectKeyOrId}/priorityscheme", "Get assigned prio...")
ASSIGN_PRIORITY_SCHEME = Endpoint("PUT", "/api/2/project/{projectKeyOrId}/priorityscheme", "Assign project with pri...")
UNASSIGN_PRIORITY_SCHEME = Endpoint("DELETE", "/api/2/project/{projectKeyOrId}/priorityscheme/{schemeId}", "Unassig...")
GET_SECURITY_LEVELS_FOR_PROJECT = Endpoint("GET", "/api/2/project/{projectKeyOrId}/securitylevel", "Get all securit...")
GET_WORKFLOW_SCHEME_FOR_PROJECT = Endpoint("GET", "/api/2/project/{projectKeyOrId}/workflowscheme", "Get workflow s...")
GET_ALL_PROJECT_CATEGORIES = Endpoint("GET", "/api/2/projectCategory", "Get all project categories")
CREATE_PROJECT_CATEGORY = Endpoint("POST", "/api/2/projectCategory", "Create project category")
REMOVE_PROJECT_CATEGORY = Endpoint("DELETE", "/api/2/projectCategory/{id}", "Delete project category")
GET_PROJECT_CATEGORY_BY_ID = Endpoint("GET", "/api/2/projectCategory/{id}", "Get project category by ID")
UPDATE_PROJECT_CATEGORY = Endpoint("PUT", "/api/2/projectCategory/{id}", "Update project category")
SEARCH_FOR_PROJECTS = Endpoint("GET", "/api/2/projects/picker", "Get projects matching query")
GET_PROJECT_1 = Endpoint("GET", "/api/2/projectvalidate/key", "Get project key validation")
GET_PROJECT_ROLES_1 = Endpoint("GET", "/api/2/role", "Get all project roles")
CREATE_PROJECT_ROLE = Endpoint("POST", "/api/2/role", "Create a new project role")
DELETE_PROJECT_ROLE = Endpoint("DELETE", "/api/2/role/{id}", "Deletes a role")
GET_PROJECT_ROLES_BY_ID = Endpoint("GET", "/api/2/role/{id}", "Get a specific project role")
PARTIAL_UPDATE_PROJECT_ROLE = Endpoint("POST", "/api/2/role/{id}", "Partially updates a role's name or description")
FULLY_UPDATE_PROJECT_ROLE = Endpoint("PUT", "/api/2/role/{id}", "Fully updates a role's name and description")
DELETE_PROJECT_ROLE_ACTORS_FROM_ROLE = Endpoint("DELETE", "/api/2/role/{id}/actors", "Removes default actor from a ...")
GET_PROJECT_ROLE_ACTORS_FOR_ROLE = Endpoint("GET", "/api/2/role/{id}/actors", "Get default actors for a role")
ADD_PROJECT_ROLE_ACTORS_TO_ROLE = Endpoint("POST", "/api/2/role/{id}/actors", "Adds default actors to a role")
GET_PAGINATED_VERSIONS = Endpoint("GET", "/api/2/version", "Get paginated versions")
CREATE_VERSION = Endpoint("POST", "/api/2/version", "Create new version")
GET_REMOTE_VERSION_LINKS = Endpoint("GET", "/api/2/version/remotelink", "Get remote version links by global ID")
GET_VERSION = Endpoint("GET", "/api/2/version/{id}", "Get version details")
UPDATE_VERSION = Endpoint("PUT", "/api/2/version/{id}", "Update version details")
MERGE = Endpoint("PUT", "/api/2/version/{id}/mergeto/{moveIssuesTo}", "Merge versions")
MOVE_VERSION = Endpoint("POST", "/api/2/version/{id}/move", "Modify version's sequence")
GET_VERSION_RELATED_ISSUES = Endpoint("GET", "/api/2/version/{id}/relatedIssueCounts", "Get version related issues ...")
DELETE_1 = Endpoint("POST", "/api/2/version/{id}/removeAndSwap", "Delete version and replace values")
GET_VERSION_UNRESOLVED_ISSUES = Endpoint("GET", "/api/2/version/{id}/unresolvedIssueCount", "Get version unresolved...")
DELETE_REMOTE_VERSION_LINKS_BY_VERSION_ID = Endpoint("DELETE", "/api/2/version/{versionId}/remotelink", "Delete all...")
GET_REMOTE_VERSION_LINKS_BY_VERSION_ID = Endpoint("GET", "/api/2/version/{versionId}/remotelink", "Get remote versi...")
CREATE_OR_UPDATE_REMOTE_VERSION_LINK = Endpoint("POST", "/api/2/version/{versionId}/remotelink", "Create or update ...")
DELETE_REMOTE_VERSION_LINK = Endpoint("DELETE", "/api/2/version/{versionId}/remotelink/{globalId}", "Delete specifi...")
GET_REMOTE_VERSION_LINK = Endpoint("GET", "/api/2/version/{versionId}/remotelink/{globalId}", "Get specific remote ...")
CREATE_OR_UPDATE_REMOTE_VERSION_LINK_1 = Endpoint("POST", "/api/2/version/{versionId}/remotelink/{globalId}", "Crea...")

# --- Issue ---

RANK_ISSUES = Endpoint("PUT", "/agile/1.0/issue/rank", "Rank issues before or after a given issue")
GET_ISSUE_1_0_ISSUE = Endpoint("GET", "/agile/1.0/issue/{issueIdOrKey}", "Get a single issue with Agile fields")
GET_ISSUE_ESTIMATION_FOR_BOARD = Endpoint("GET", "/agile/1.0/issue/{issueIdOrKey}/estimation", "Get the estimation ...")
ESTIMATE_ISSUE_FOR_BOARD = Endpoint("PUT", "/agile/1.0/issue/{issueIdOrKey}/estimation", "Update the estimation of ...")
GET_ATTACHMENT_META = Endpoint("GET", "/api/2/attachment/meta", "Get attachment capabilities")
REMOVE_ATTACHMENT = Endpoint("DELETE", "/api/2/attachment/{id}", "Delete an attachment from an issue")
GET_ATTACHMENT = Endpoint("GET", "/api/2/attachment/{id}", "Get the meta-data for an attachment, including the URI ...")
EXPAND_FOR_HUMANS = Endpoint("GET", "/api/2/attachment/{id}/expand/human", "Get human-readable attachment expansion")
EXPAND_FOR_MACHINES = Endpoint("GET", "/api/2/attachment/{id}/expand/raw", "Get raw attachment expansion")
GET_PROPERTIES_KEYS_1_COMMENT_PROPERTIES = Endpoint("GET", "/api/2/comment/{commentId}/properties", "Get properties...")
DELETE_PROPERTY_2 = Endpoint("DELETE", "/api/2/comment/{commentId}/properties/{propertyKey}", "Delete a property fr...")
GET_PROPERTY_2 = Endpoint("GET", "/api/2/comment/{commentId}/properties/{propertyKey}", "Get a property from a comment")
SET_PROPERTY_1_COMMENT_PROPERTIES = Endpoint("PUT", "/api/2/comment/{commentId}/properties/{propertyKey}", "Set a p...")
CREATE_ISSUE = Endpoint("POST", "/api/2/issue", "Create an issue or sub-task from json")
ARCHIVE_ISSUES = Endpoint("POST", "/api/2/issue/archive", "Archive list of issues")
CREATE_ISSUES = Endpoint("POST", "/api/2/issue/bulk", "Create an issue or sub-task from json - bulk operation.")
GET_CREATE_ISSUE_META_PROJECT_ISSUE_TYPES = Endpoint("GET", "/api/2/issue/createmeta/{projectIdOrKey}/issuetypes", "Ge")
GET_CREATE_ISSUE_META_FIELDS = Endpoint("GET", "/api/2/issue/createmeta/{projectIdOrKey}/issuetypes/{issueTypeId}", "G")
GET_ISSUE_PICKER_RESOURCE = Endpoint("GET", "/api/2/issue/picker", "Get suggested issues for auto-completion")
DELETE_ISSUE = Endpoint("DELETE", "/api/2/issue/{issueIdOrKey}", "Delete an issue")
GET_ISSUE_2_ISSUE = Endpoint("GET", "/api/2/issue/{issueIdOrKey}", "Get issue for key")
EDIT_ISSUE = Endpoint("PUT", "/api/2/issue/{issueIdOrKey}", "Edit an issue from a JSON representation")
ARCHIVE_ISSUE = Endpoint("PUT", "/api/2/issue/{issueIdOrKey}/archive", "Archive an issue")
ASSIGN = Endpoint("PUT", "/api/2/issue/{issueIdOrKey}/assignee", "Assign an issue to a user")
ADD_ATTACHMENT = Endpoint("POST", "/api/2/issue/{issueIdOrKey}/attachments", "Add one or more attachments to an issue")
GET_COMMENTS = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/comment", "Get comments for an issue")
ADD_COMMENT = Endpoint("POST", "/api/2/issue/{issueIdOrKey}/comment", "Add a comment")
DELETE_COMMENT = Endpoint("DELETE", "/api/2/issue/{issueIdOrKey}/comment/{id}", "Delete a comment")
GET_COMMENT = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/comment/{id}", "Get a comment by id")
UPDATE_COMMENT = Endpoint("PUT", "/api/2/issue/{issueIdOrKey}/comment/{id}", "Update a comment")
SET_PIN_COMMENT = Endpoint("PUT", "/api/2/issue/{issueIdOrKey}/comment/{id}/pin", "Pin a comment")
GET_EDIT_ISSUE_META = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/editmeta", "Get metadata for issue types used fo...")
NOTIFY = Endpoint("POST", "/api/2/issue/{issueIdOrKey}/notify", "Send notification to recipients")
GET_PINNED_COMMENTS = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/pinned-comments", "Get pinned comments for an issue")
GET_PROPERTIES_KEYS_2 = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/properties", "Get keys of all properties for a...")
DELETE_PROPERTY_3 = Endpoint("DELETE", "/api/2/issue/{issueIdOrKey}/properties/{propertyKey}", "Delete a property f...")
GET_PROPERTY_3 = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/properties/{propertyKey}", "Get the value of a specif...")
SET_PROPERTY_2 = Endpoint("PUT", "/api/2/issue/{issueIdOrKey}/properties/{propertyKey}", "Update the value of a spe...")
DELETE_REMOTE_ISSUE_LINK_BY_GLOBAL_ID = Endpoint("DELETE", "/api/2/issue/{issueIdOrKey}/remotelink", "Delete remote...")
GET_REMOTE_ISSUE_LINKS = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/remotelink", "Get remote issue links for an i...")
CREATE_OR_UPDATE_REMOTE_ISSUE_LINK = Endpoint("POST", "/api/2/issue/{issueIdOrKey}/remotelink", "Create or update r...")
DELETE_REMOTE_ISSUE_LINK_BY_ID = Endpoint("DELETE", "/api/2/issue/{issueIdOrKey}/remotelink/{linkId}", "Delete remo...")
GET_REMOTE_ISSUE_LINK_BY_ID = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/remotelink/{linkId}", "Get a remote issu...")
UPDATE_REMOTE_ISSUE_LINK = Endpoint("PUT", "/api/2/issue/{issueIdOrKey}/remotelink/{linkId}", "Update remote issue ...")
RESTORE_ISSUE = Endpoint("PUT", "/api/2/issue/{issueIdOrKey}/restore", "Restore an archived issue")
GET_SUB_TASKS = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/subtask", "Get an issue's subtask list")
CAN_MOVE_SUB_TASK = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/subtask/move", "Check if a subtask can be moved")
MOVE_SUB_TASKS = Endpoint("POST", "/api/2/issue/{issueIdOrKey}/subtask/move", "Reorder an issue's subtasks")
GET_TRANSITIONS = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/transitions", "Get list of transitions possible for ...")
DO_TRANSITION = Endpoint("POST", "/api/2/issue/{issueIdOrKey}/transitions", "Perform a transition on an issue")
REMOVE_VOTE = Endpoint("DELETE", "/api/2/issue/{issueIdOrKey}/votes", "Remove vote from issue")
GET_VOTES = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/votes", "Get votes for issue")
ADD_VOTE = Endpoint("POST", "/api/2/issue/{issueIdOrKey}/votes", "Add vote to issue")
REMOVE_WATCHER_1 = Endpoint("DELETE", "/api/2/issue/{issueIdOrKey}/watchers", "Delete watcher from issue")
GET_ISSUE_WATCHERS = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/watchers", "Get list of watchers of issue")
ADD_WATCHER_1 = Endpoint("POST", "/api/2/issue/{issueIdOrKey}/watchers", "Add a user as watcher")
GET_ISSUE_WORKLOG = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/worklog", "Get worklogs for an issue")
ADD_WORKLOG = Endpoint("POST", "/api/2/issue/{issueIdOrKey}/worklog", "Add a worklog entry")
DELETE_WORKLOG = Endpoint("DELETE", "/api/2/issue/{issueIdOrKey}/worklog/{id}", "Delete a worklog entry")
GET_WORKLOG = Endpoint("GET", "/api/2/issue/{issueIdOrKey}/worklog/{id}", "Get a worklog by id")
UPDATE_WORKLOG = Endpoint("PUT", "/api/2/issue/{issueIdOrKey}/worklog/{id}", "Update a worklog entry")
LINK_ISSUES = Endpoint("POST", "/api/2/issueLink", "Create an issue link between two issues")
DELETE_ISSUE_LINK = Endpoint("DELETE", "/api/2/issueLink/{linkId}", "Delete an issue link with the specified id")
GET_ISSUE_LINK = Endpoint("GET", "/api/2/issueLink/{linkId}", "Get an issue link with the specified id")
GET_ISSUE_LINK_TYPES = Endpoint("GET", "/api/2/issueLinkType", "Get list of available issue link types")
CREATE_ISSUE_LINK_TYPE = Endpoint("POST", "/api/2/issueLinkType", "Create a new issue link type")
DELETE_ISSUE_LINK_TYPE = Endpoint("DELETE", "/api/2/issueLinkType/{issueLinkTypeId}", "Delete the specified issue l...")
GET_ISSUE_LINK_TYPE = Endpoint("GET", "/api/2/issueLinkType/{issueLinkTypeId}", "Get information about an issue lin...")
UPDATE_ISSUE_LINK_TYPE = Endpoint("PUT", "/api/2/issueLinkType/{issueLinkTypeId}", "Update the specified issue link...")
GET_AUTO_COMPLETE = Endpoint("GET", "/api/2/jql/autocompletedata", "Get auto complete data for JQL searches")
GET_FIELD_AUTO_COMPLETE_FOR_QUERY_STRING = Endpoint("GET", "/api/2/jql/autocompletedata/suggestions", "Get auto com...")
SEARCH_1 = Endpoint("GET", "/api/2/search", "Get issues using JQL")
SEARCH_USING_SEARCH_REQUEST = Endpoint("POST", "/api/2/search", "Perform search with JQL")
GET_IDS_OF_WORKLOGS_DELETED_SINCE = Endpoint("GET", "/api/2/worklog/deleted", "Returns worklogs deleted since given...")
GET_WORKLOGS_FOR_IDS = Endpoint("POST", "/api/2/worklog/list", "Returns worklogs for given ids.")
GET_IDS_OF_WORKLOGS_MODIFIED_SINCE = Endpoint("GET", "/api/2/worklog/updated", "Returns worklogs updated since give...")

# --- IssueMeta ---

GET_CUSTOM_FIELD_OPTION = Endpoint("GET", "/api/2/customFieldOption/{id}", "Get custom field option by ID")
BULK_DELETE_CUSTOM_FIELDS = Endpoint("DELETE", "/api/2/customFields", "Delete custom fields in bulk")
GET_CUSTOM_FIELDS = Endpoint("GET", "/api/2/customFields", "Get custom fields with pagination")
GET_CUSTOM_FIELD_OPTIONS = Endpoint("GET", "/api/2/customFields/{customFieldId}/options", "Get custom field options")
GET_FIELDS = Endpoint("GET", "/api/2/field", "Get all fields, both System and Custom")
CREATE_CUSTOM_FIELD = Endpoint("POST", "/api/2/field", "Create a custom field using a definition")
GET_ISSUE_ALL_TYPES = Endpoint("GET", "/api/2/issuetype", "Get list of all issue types visible to user")
CREATE_ISSUE_TYPE = Endpoint("POST", "/api/2/issuetype", "Create an issue type from JSON representation")
GET_PAGINATED_ISSUE_TYPES = Endpoint("GET", "/api/2/issuetype/page", "Get paginated list of filtered issue types")
DELETE_ISSUE_TYPE_1 = Endpoint("DELETE", "/api/2/issuetype/{id}", "Delete specified issue type and migrate associat...")
GET_ISSUE_TYPE_1 = Endpoint("GET", "/api/2/issuetype/{id}", "Get full representation of issue type by id")
UPDATE_ISSUE_TYPE = Endpoint("PUT", "/api/2/issuetype/{id}", "Update specified issue type from JSON representation")
GET_ALTERNATIVE_ISSUE_TYPES = Endpoint("GET", "/api/2/issuetype/{id}/alternatives", "Get list of alternative issue ...")
CREATE_AVATAR_FROM_TEMPORARY_1 = Endpoint("POST", "/api/2/issuetype/{id}/avatar", "Convert temporary avatar into a ...")
STORE_TEMPORARY_AVATAR_USING_MULTI_PART = Endpoint("POST", "/api/2/issuetype/{id}/avatar/temporary", "Create tempor...")
GET_PROPERTY_KEYS = Endpoint("GET", "/api/2/issuetype/{issueTypeId}/properties", "Get all properties keys for issue...")
DELETE_PROPERTY_4 = Endpoint("DELETE", "/api/2/issuetype/{issueTypeId}/properties/{propertyKey}", "Delete specified...")
GET_PROPERTY_4 = Endpoint("GET", "/api/2/issuetype/{issueTypeId}/properties/{propertyKey}", "Get value of specified...")
SET_PROPERTY_3 = Endpoint("PUT", "/api/2/issuetype/{issueTypeId}/properties/{propertyKey}", "Update specified issue...")
GET_ALL_ISSUE_TYPE_SCHEMES = Endpoint("GET", "/api/2/issuetypescheme", "Get list of all issue type schemes visible ...")
CREATE_ISSUE_TYPE_SCHEME = Endpoint("POST", "/api/2/issuetypescheme", "Create an issue type scheme from JSON repres...")
DELETE_ISSUE_TYPE_SCHEME = Endpoint("DELETE", "/api/2/issuetypescheme/{schemeId}", "Delete specified issue type scheme")
GET_ISSUE_TYPE_SCHEME = Endpoint("GET", "/api/2/issuetypescheme/{schemeId}", "Get full representation of issue type...")
UPDATE_ISSUE_TYPE_SCHEME = Endpoint("PUT", "/api/2/issuetypescheme/{schemeId}", "Update specified issue type scheme...")
REMOVE_ALL_PROJECT_ASSOCIATIONS = Endpoint("DELETE", "/api/2/issuetypescheme/{schemeId}/associations", "Remove all ...")
GET_ASSOCIATED_PROJECTS = Endpoint("GET", "/api/2/issuetypescheme/{schemeId}/associations", "Get all of the associa...")
ADD_PROJECT_ASSOCIATIONS_TO_SCHEME = Endpoint("POST", "/api/2/issuetypescheme/{schemeId}/associations", "Add projec...")
SET_PROJECT_ASSOCIATIONS_FOR_SCHEME = Endpoint("PUT", "/api/2/issuetypescheme/{schemeId}/associations", "Set projec...")
REMOVE_PROJECT_ASSOCIATION = Endpoint("DELETE", "/api/2/issuetypescheme/{schemeId}/associations/{projIdOrKey}", "Re...")
GET_PRIORITIES = Endpoint("GET", "/api/2/priority", "Get all issue priorities")
GET_PRIORITIES_1 = Endpoint("GET", "/api/2/priority/page", "Get paginated issue priorities")
GET_PRIORITY = Endpoint("GET", "/api/2/priority/{id}", "Get an issue priority by ID")
GET_PRIORITY_SCHEMES = Endpoint("GET", "/api/2/priorityschemes", "Get all priority schemes")
CREATE_PRIORITY_SCHEME = Endpoint("POST", "/api/2/priorityschemes", "Create new priority scheme")
DELETE_PRIORITY_SCHEME = Endpoint("DELETE", "/api/2/priorityschemes/{schemeId}", "Delete a priority scheme")
GET_PRIORITY_SCHEME = Endpoint("GET", "/api/2/priorityschemes/{schemeId}", "Get a priority scheme by ID")
UPDATE_PRIORITY_SCHEME = Endpoint("PUT", "/api/2/priorityschemes/{schemeId}", "Update a priority scheme")
GET_RESOLUTIONS = Endpoint("GET", "/api/2/resolution", "Get all resolutions")
GET_PAGINATED_RESOLUTIONS = Endpoint("GET", "/api/2/resolution/page", "Get paginated filtered resolutions")
GET_RESOLUTION = Endpoint("GET", "/api/2/resolution/{id}", "Get a resolution by ID")
GET_ALL_SCREENS = Endpoint("GET", "/api/2/screens", "Get available field screens")
ADD_FIELD_TO_DEFAULT_SCREEN = Endpoint("POST", "/api/2/screens/addToDefault/{fieldId}", "Add field to default screen")
GET_FIELDS_TO_ADD = Endpoint("GET", "/api/2/screens/{screenId}/availableFields", "Get available fields for screen")
GET_ALL_TABS = Endpoint("GET", "/api/2/screens/{screenId}/tabs", "Get all tabs for a screen")
ADD_TAB = Endpoint("POST", "/api/2/screens/{screenId}/tabs", "Create tab for a screen")
DELETE_TAB = Endpoint("DELETE", "/api/2/screens/{screenId}/tabs/{tabId}", "Delete a tab from a screen")
RENAME_TAB = Endpoint("PUT", "/api/2/screens/{screenId}/tabs/{tabId}", "Rename a tab on a screen")
GET_ALL_FIELDS = Endpoint("GET", "/api/2/screens/{screenId}/tabs/{tabId}/fields", "Get all fields for a tab")
ADD_FIELD = Endpoint("POST", "/api/2/screens/{screenId}/tabs/{tabId}/fields", "Add field to a tab")
REMOVE_FIELD = Endpoint("DELETE", "/api/2/screens/{screenId}/tabs/{tabId}/fields/{id}", "Remove field from tab")
MOVE_FIELD = Endpoint("POST", "/api/2/screens/{screenId}/tabs/{tabId}/fields/{id}/move", "Move field on a tab")
UPDATE_SHOW_WHEN_EMPTY_INDICATOR = Endpoint(
    "PUT",
    "/api/2/screens/{screenId}/tabs/{tabId}/fields/{id}/updateShowWhenEmptyIndicator/{newValue}",
    "",
)
MOVE_TAB = Endpoint("POST", "/api/2/screens/{screenId}/tabs/{tabId}/move/{pos}", "Move tab position")
GET_STATUSES = Endpoint("GET", "/api/2/status", "Get all statuses")
GET_PAGINATED_STATUSES = Endpoint("GET", "/api/2/status/page", "Get paginated filtered statuses")
GET_STATUS = Endpoint("GET", "/api/2/status/{idOrName}", "Get status by ID or name")
GET_STATUS_CATEGORIES = Endpoint("GET", "/api/2/statuscategory", "Get all status categories")
GET_STATUS_CATEGORY = Endpoint("GET", "/api/2/statuscategory/{idOrKey}", "Get status category by ID or key")
GET_ALL_WORKFLOWS = Endpoint("GET", "/api/2/workflow", "Get all workflows")
CREATE_SCHEME = Endpoint("POST", "/api/2/workflowscheme", "Create a new workflow scheme")
DELETE_SCHEME = Endpoint("DELETE", "/api/2/workflowscheme/{id}", "Delete the specified workflow scheme")
GET_BY_ID = Endpoint("GET", "/api/2/workflowscheme/{id}", "Get requested workflow scheme by ID")
UPDATE = Endpoint("PUT", "/api/2/workflowscheme/{id}", "Update a specified workflow scheme")
CREATE_DRAFT_FOR_PARENT = Endpoint("POST", "/api/2/workflowscheme/{id}/createdraft", "Create a draft for a workflow...")
DELETE_DEFAULT = Endpoint("DELETE", "/api/2/workflowscheme/{id}/default", "Remove default workflow from a scheme")
GET_DEFAULT = Endpoint("GET", "/api/2/workflowscheme/{id}/default", "Get default workflow for a scheme")
UPDATE_DEFAULT = Endpoint("PUT", "/api/2/workflowscheme/{id}/default", "Update default workflow for a scheme")
DELETE_DRAFT_BY_ID = Endpoint("DELETE", "/api/2/workflowscheme/{id}/draft", "Delete the specified draft workflow sc...")
GET_DRAFT_BY_ID = Endpoint("GET", "/api/2/workflowscheme/{id}/draft", "Get requested draft workflow scheme by ID")
UPDATE_DRAFT = Endpoint("PUT", "/api/2/workflowscheme/{id}/draft", "Update a draft workflow scheme")
DELETE_DRAFT_DEFAULT = Endpoint("DELETE", "/api/2/workflowscheme/{id}/draft/default", "Remove default workflow from...")
GET_DRAFT_DEFAULT = Endpoint("GET", "/api/2/workflowscheme/{id}/draft/default", "Get default workflow for a draft s...")
UPDATE_DRAFT_DEFAULT = Endpoint("PUT", "/api/2/workflowscheme/{id}/draft/default", "Update default workflow for a d...")
DELETE_DRAFT_ISSUE_TYPE = Endpoint("DELETE", "/api/2/workflowscheme/{id}/draft/issuetype/{issueType}", "Delete an i...")
GET_DRAFT_ISSUE_TYPE = Endpoint("GET", "/api/2/workflowscheme/{id}/draft/issuetype/{issueType}", "Get issue type ma...")
SET_DRAFT_ISSUE_TYPE = Endpoint("PUT", "/api/2/workflowscheme/{id}/draft/issuetype/{issueType}", "Set an issue type...")
DELETE_DRAFT_WORKFLOW_MAPPING = Endpoint("DELETE", "/api/2/workflowscheme/{id}/draft/workflow", "Delete a workflow ...")
GET_DRAFT_WORKFLOW = Endpoint("GET", "/api/2/workflowscheme/{id}/draft/workflow", "Get draft workflow mappings")
UPDATE_DRAFT_WORKFLOW_MAPPING = Endpoint("PUT", "/api/2/workflowscheme/{id}/draft/workflow", "Update a workflow map...")
DELETE_ISSUE_TYPE = Endpoint("DELETE", "/api/2/workflowscheme/{id}/issuetype/{issueType}", "Delete an issue type ma...")
GET_ISSUE_TYPE = Endpoint("GET", "/api/2/workflowscheme/{id}/issuetype/{issueType}", "Get issue type mapping for a ...")
SET_ISSUE_TYPE = Endpoint("PUT", "/api/2/workflowscheme/{id}/issuetype/{issueType}", "Set an issue type mapping for...")
DELETE_WORKFLOW_MAPPING = Endpoint("DELETE", "/api/2/workflowscheme/{id}/workflow", "Delete a workflow mapping from...")
GET_WORKFLOW = Endpoint("GET", "/api/2/workflowscheme/{id}/workflow", "Get workflow mappings for a scheme")
UPDATE_WORKFLOW_MAPPING = Endpoint("PUT", "/api/2/workflowscheme/{id}/workflow", "Update a workflow mapping in a sc...")

# --- PermissionSecurity ---

GET_ISSUE_SECURITY_SCHEMES = Endpoint("GET", "/api/2/issuesecurityschemes", "Get all issue security schemes")
GET_ISSUE_SECURITY_SCHEME = Endpoint("GET", "/api/2/issuesecurityschemes/{id}", "Get specific issue security scheme...")
GET_PERMISSIONS = Endpoint("GET", "/api/2/mypermissions", "Get permissions for the logged in user")
GET_NOTIFICATION_SCHEMES = Endpoint("GET", "/api/2/notificationscheme", "Get paginated notification schemes")
GET_NOTIFICATION_SCHEME = Endpoint("GET", "/api/2/notificationscheme/{id}", "Get full notification scheme details")
GET_ALL_PERMISSIONS = Endpoint("GET", "/api/2/permissions", "Get all permissions present in Jira instance")
GET_PERMISSION_SCHEMES = Endpoint("GET", "/api/2/permissionscheme", "Get all permission schemes")
CREATE_PERMISSION_SCHEME = Endpoint("POST", "/api/2/permissionscheme", "Create a new permission scheme")
GET_SCHEME_ATTRIBUTE = Endpoint("GET", "/api/2/permissionscheme/{permissionSchemeId}/attribute/{attributeKey}", "Ge...")
SET_SCHEME_ATTRIBUTE = Endpoint("PUT", "/api/2/permissionscheme/{permissionSchemeId}/attribute/{key}", "Update or i...")
DELETE_PERMISSION_SCHEME = Endpoint("DELETE", "/api/2/permissionscheme/{schemeId}", "Delete a permission scheme by ID")
GET_PERMISSION_SCHEME = Endpoint("GET", "/api/2/permissionscheme/{schemeId}", "Get a permission scheme by ID")
UPDATE_PERMISSION_SCHEME = Endpoint("PUT", "/api/2/permissionscheme/{schemeId}", "Update a permission scheme")
GET_PERMISSION_SCHEME_GRANTS = Endpoint("GET", "/api/2/permissionscheme/{schemeId}/permission", "Get all permission...")
CREATE_PERMISSION_GRANT = Endpoint("POST", "/api/2/permissionscheme/{schemeId}/permission", "Create a permission gr...")
DELETE_PERMISSION_SCHEME_ENTITY = Endpoint("DELETE", "/api/2/permissionscheme/{schemeId}/permission/{permissionId}", "")
GET_PERMISSION_SCHEME_GRANT = Endpoint("GET", "/api/2/permissionscheme/{schemeId}/permission/{permissionId}", "Get ...")
GET_ISSUESECURITYLEVEL = Endpoint("GET", "/api/2/securitylevel/{id}", "Get a security level by ID")

# --- User ---

GET_ALL = Endpoint("GET", "/api/2/applicationrole", "Get all application roles in the system")
PUT_BULK = Endpoint("PUT", "/api/2/applicationrole", "Update application roles")
GET_4 = Endpoint("GET", "/api/2/applicationrole/{key}", "Get application role by key")
PUT_2 = Endpoint("PUT", "/api/2/applicationrole/{key}", "Update application role")
FIND_USERS_AND_GROUPS = Endpoint("GET", "/api/2/groupuserpicker", "Get users and groups matching query with highlig...")
REMOVE_PREFERENCE = Endpoint("DELETE", "/api/2/mypreferences", "Delete user preference")
GET_PREFERENCE = Endpoint("GET", "/api/2/mypreferences", "Get user preference by key")
SET_PREFERENCE = Endpoint("PUT", "/api/2/mypreferences", "Update user preference")
GET_USER = Endpoint("GET", "/api/2/myself", "Get currently logged user")
UPDATE_USER = Endpoint("PUT", "/api/2/myself", "Update currently logged user")
CHANGE_MY_PASSWORD = Endpoint("PUT", "/api/2/myself/password", "Update caller password")
REMOVE_USER = Endpoint("DELETE", "/api/2/user", "Delete user")
GET_USER_1 = Endpoint("GET", "/api/2/user", "Get user by username or key")
CREATE_USER = Endpoint("POST", "/api/2/user", "Create new user")
UPDATE_USER_1 = Endpoint("PUT", "/api/2/user", "Update user details")
GET_A11Y_PERSONAL_SETTINGS = Endpoint("GET", "/api/2/user/a11y/personal-settings", "Get available accessibility per...")
VALIDATE_USER_ANONYMIZATION = Endpoint("GET", "/api/2/user/anonymization", "Get validation for user anonymization")
SCHEDULE_USER_ANONYMIZATION = Endpoint("POST", "/api/2/user/anonymization", "Schedule user anonymization")
GET_PROGRESS_1 = Endpoint("GET", "/api/2/user/anonymization/progress", "Get user anonymization progress")
VALIDATE_USER_ANONYMIZATION_RERUN = Endpoint("GET", "/api/2/user/anonymization/rerun", "Get validation for user ano...")
SCHEDULE_USER_ANONYMIZATION_RERUN = Endpoint("POST", "/api/2/user/anonymization/rerun", "Schedule user anonymizatio...")
UNLOCK_ANONYMIZATION = Endpoint("DELETE", "/api/2/user/anonymization/unlock", "Delete stale user anonymization task")
REMOVE_USER_FROM_APPLICATION_1 = Endpoint("DELETE", "/api/2/user/application", "Remove user from application")
ADD_USER_TO_APPLICATION_1 = Endpoint("POST", "/api/2/user/application", "Add user to application")
FIND_BULK_ASSIGNABLE_USERS = Endpoint("GET", "/api/2/user/assignable/multiProjectSearch", "Find bulk assignable users")
FIND_ASSIGNABLE_USERS_1 = Endpoint("GET", "/api/2/user/assignable/search", "Find assignable users by username")
CREATE_AVATAR_FROM_TEMPORARY_4 = Endpoint("POST", "/api/2/user/avatar", "Create avatar from temporary")
UPDATE_USER_AVATAR_1 = Endpoint("PUT", "/api/2/user/avatar", "Update user avatar")
STORE_TEMPORARY_AVATAR_USING_MULTI_PART_3 = Endpoint("POST", "/api/2/user/avatar/temporary", "Store temporary avata...")
DELETE_AVATAR_2 = Endpoint("DELETE", "/api/2/user/avatar/{id}", "Delete avatar")
GET_ALL_AVATARS_1 = Endpoint("GET", "/api/2/user/avatars", "Get all avatars for user")
RESET_COLUMNS = Endpoint("DELETE", "/api/2/user/columns", "Reset default columns to system default")
DEFAULT_COLUMNS = Endpoint("GET", "/api/2/user/columns", "Get default columns for user")
SET_COLUMNS_URL_ENCODED = Endpoint("PUT", "/api/2/user/columns", "Set default columns for user")
GET_DUPLICATED_USERS_COUNT = Endpoint("GET", "/api/2/user/duplicated/count", "Get duplicated users count")
GET_DUPLICATED_USERS_MAPPING = Endpoint("GET", "/api/2/user/duplicated/list", "Get duplicated users mapping")
GET_USER_LIST = Endpoint("GET", "/api/2/user/list", "List all users")
CHANGE_USER_PASSWORD = Endpoint("PUT", "/api/2/user/password", "Update user password")
FIND_USERS_WITH_ALL_PERMISSIONS = Endpoint("GET", "/api/2/user/permission/search", "Find users with all specified p...")
FIND_USERS_FOR_PICKER = Endpoint("GET", "/api/2/user/picker", "Find users for picker by query")
GET_PROPERTIES_KEYS_4 = Endpoint("GET", "/api/2/user/properties", "Get keys of all properties for a user")
DELETE_PROPERTY_6 = Endpoint("DELETE", "/api/2/user/properties/{propertyKey}", "Delete a specified user's property")
GET_PROPERTY_6 = Endpoint("GET", "/api/2/user/properties/{propertyKey}", "Get the value of a specified user's property")
SET_PROPERTY_5 = Endpoint("PUT", "/api/2/user/properties/{propertyKey}", "Set the value of a specified user's property")
FIND_USERS = Endpoint("GET", "/api/2/user/search", "Find users by username")
DELETE_SESSION = Endpoint("DELETE", "/api/2/user/session/{username}", "Delete user session")
FIND_USERS_WITH_BROWSE_PERMISSION = Endpoint("GET", "/api/2/user/viewissue/search", "Find users with browse permission")

# --- Group ---

REMOVE_GROUP = Endpoint("DELETE", "/api/2/group", "Delete a specified group")
CREATE_GROUP = Endpoint("POST", "/api/2/group", "Create a group with given parameters")
GET_USERS_FROM_GROUP = Endpoint("GET", "/api/2/group/member", "Get users from a specified group")
REMOVE_USER_FROM_GROUP = Endpoint("DELETE", "/api/2/group/user", "Remove a user from a specified group")
ADD_USER_TO_GROUP = Endpoint("POST", "/api/2/group/user", "Add a user to a specified group")
FIND_GROUPS = Endpoint("GET", "/api/2/groups/picker", "Get groups matching a query")

# --- Avatar ---

GET_ALL_SYSTEM_AVATARS = Endpoint("GET", "/api/2/avatar/{type}/system", "Get all system avatars")
STORE_TEMPORARY_AVATAR = Endpoint("POST", "/api/2/avatar/{type}/temporary", "Create temporary avatar")
CREATE_AVATAR_FROM_TEMPORARY = Endpoint("POST", "/api/2/avatar/{type}/temporaryCrop", "Update avatar cropping")
GET_AVATARS = Endpoint("GET", "/api/2/universal_avatar/type/{type}/owner/{owningObjectId}", "Get all avatars for a ...")
CREATE_AVATAR_FROM_TEMPORARY_3 = Endpoint(
    "POST",
    "/api/2/universal_avatar/type/{type}/owner/{owningObjectId}/avatar",
    "",
)
DELETE_AVATAR_1 = Endpoint("DELETE", "/api/2/universal_avatar/type/{type}/owner/{owningObjectId}/avatar/{id}", "Del...")
STORE_TEMPORARY_AVATAR_USING_MULTI_PART_2 = Endpoint(
    "POST",
    "/api/2/universal_avatar/type/{type}/owner/{owningObjectId}/temp",
    "",
)

# --- DashboardFilter ---

LIST = Endpoint("GET", "/api/2/dashboard", "Get all dashboards with optional filtering")
GET_PROPERTIES_KEYS_ITEMS_PROPERTIES = Endpoint("GET", "/api/2/dashboard/{dashboardId}/items/{itemId}/properties", "Ge")
DELETE_PROPERTY_1_ITEMS_PROPERTIES = Endpoint(
    "DELETE",
    "/api/2/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}",
    "",
)
GET_PROPERTY_1_ITEMS_PROPERTIES = Endpoint(
    "GET",
    "/api/2/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}",
    "",
)
SET_PROPERTY_ITEMS_PROPERTIES = Endpoint(
    "PUT",
    "/api/2/dashboard/{dashboardId}/items/{itemId}/properties/{propertyKey}",
    "",
)
GET_DASHBOARD = Endpoint("GET", "/api/2/dashboard/{id}", "Get a single dashboard by ID")
CREATE_FILTER = Endpoint("POST", "/api/2/filter", "Create a new filter")
GET_DEFAULT_SHARE_SCOPE = Endpoint("GET", "/api/2/filter/defaultShareScope", "Get default share scope")
SET_DEFAULT_SHARE_SCOPE = Endpoint("PUT", "/api/2/filter/defaultShareScope", "Set default share scope")
GET_FAVOURITE_FILTERS = Endpoint("GET", "/api/2/filter/favourite", "Get favourite filters")
DELETE_FILTER = Endpoint("DELETE", "/api/2/filter/{id}", "Delete a filter")
GET_FILTER = Endpoint("GET", "/api/2/filter/{id}", "Get a filter by ID")
EDIT_FILTER = Endpoint("PUT", "/api/2/filter/{id}", "Update an existing filter")
RESET_COLUMNS_1 = Endpoint("DELETE", "/api/2/filter/{id}/columns", "Reset columns for filter")
DEFAULT_COLUMNS_1 = Endpoint("GET", "/api/2/filter/{id}/columns", "Get default columns for filter")
SET_COLUMNS_1 = Endpoint("PUT", "/api/2/filter/{id}/columns", "Set default columns for filter")
GET_SHARE_PERMISSIONS = Endpoint("GET", "/api/2/filter/{id}/permission", "Get all share permissions of filter")
ADD_SHARE_PERMISSION = Endpoint("POST", "/api/2/filter/{id}/permission", "Add share permissions to filter")
DELETE_SHARE_PERMISSION = Endpoint("DELETE", "/api/2/filter/{id}/permission/{permission-id}", "Remove share permiss...")
GET_SHARE_PERMISSION = Endpoint("GET", "/api/2/filter/{id}/permission/{permissionId}", "Get a single share permissi...")

# --- System ---

GET_PROPERTY_2_APPLICATION_PROPERTIES = Endpoint("GET", "/api/2/application-properties", "Get an application proper...")
GET_ADVANCED_SETTINGS = Endpoint("GET", "/api/2/application-properties/advanced-settings", "Get all advanced settin...")
SET_PROPERTY_VIA_RESTFUL_TABLE = Endpoint("PUT", "/api/2/application-properties/{id}", "Update an application property")
GET_CONFIGURATION_1 = Endpoint("GET", "/api/2/configuration", "Get Jira configuration details")
DOWNLOAD_EMAIL_TEMPLATES = Endpoint("GET", "/api/2/email-templates", "Get email templates as zip file")
UPLOAD_EMAIL_TEMPLATES = Endpoint("POST", "/api/2/email-templates", "Update email templates with zip file")
APPLY_EMAIL_TEMPLATES = Endpoint("POST", "/api/2/email-templates/apply", "Update email templates with previously up...")
REVERT_EMAIL_TEMPLATES_TO_DEFAULT = Endpoint("POST", "/api/2/email-templates/revert", "Update email templates to de...")
GET_EMAIL_TYPES = Endpoint("GET", "/api/2/email-templates/types", "Get email types for templates")
VALIDATE = Endpoint("POST", "/api/2/licenseValidator", "Validate a Jira license")
GET_SERVER_INFO = Endpoint("GET", "/api/2/serverInfo", "Get general information about the current Jira server")
SET_BASE_URL = Endpoint("PUT", "/api/2/settings/baseUrl", "Update base URL for Jira instance")
GET_ISSUE_NAVIGATOR_DEFAULT_COLUMNS = Endpoint("GET", "/api/2/settings/columns", "Get default system columns for is...")
SET_ISSUE_NAVIGATOR_DEFAULT_COLUMNS_FORM = Endpoint("PUT", "/api/2/settings/columns", "Set default system columns f...")
GET_ALL_TERMINOLOGY_ENTRIES = Endpoint("GET", "/api/2/terminology/entries", "Get all defined names for 'epic' and '...")
SET_TERMINOLOGY_ENTRIES = Endpoint("POST", "/api/2/terminology/entries", "Update epic/sprint names from original to...")
GET_TERMINOLOGY_ENTRY = Endpoint("GET", "/api/2/terminology/entries/{originalName}", "Get epic or sprint name by or...")

# --- Operations ---

REQUEST_CURRENT_INDEX_FROM_NODE = Endpoint("PUT", "/api/2/cluster/index-snapshot/{nodeId}", "Request node index sna...")
DELETE_NODE = Endpoint("DELETE", "/api/2/cluster/node/{nodeId}", "Delete a cluster node")
CHANGE_NODE_STATE_TO_OFFLINE = Endpoint("PUT", "/api/2/cluster/node/{nodeId}/offline", "Update node state to offline")
GET_ALL_NODES = Endpoint("GET", "/api/2/cluster/nodes", "Get all cluster nodes")
APPROVE_UPGRADE = Endpoint("POST", "/api/2/cluster/zdu/approve", "Approve cluster upgrade")
CANCEL_UPGRADE = Endpoint("POST", "/api/2/cluster/zdu/cancel", "Cancel cluster upgrade")
ACKNOWLEDGE_ERRORS = Endpoint("POST", "/api/2/cluster/zdu/retryUpgrade", "Retry cluster upgrade")
SET_READY_TO_UPGRADE = Endpoint("POST", "/api/2/cluster/zdu/start", "Start cluster upgrade")
GET_STATE = Endpoint("GET", "/api/2/cluster/zdu/state", "Get cluster upgrade state")
LIST_INDEX_SNAPSHOT = Endpoint("GET", "/api/2/index-snapshot", "Get list of available index snapshots")
CREATE_INDEX_SNAPSHOT = Endpoint("POST", "/api/2/index-snapshot", "Create index snapshot if not in progress")
IS_INDEX_SNAPSHOT_RUNNING = Endpoint("GET", "/api/2/index-snapshot/isRunning", "Get index snapshot creation status")
GET_INDEX_SUMMARY = Endpoint("GET", "/api/2/index/summary", "Get index condition summary")
IS_APP_MONITORING_ENABLED = Endpoint("GET", "/api/2/monitoring/app", "Get App Monitoring status")
SET_APP_MONITORING_ENABLED = Endpoint("POST", "/api/2/monitoring/app", "Update App Monitoring status")
IS_IPD_MONITORING_ENABLED = Endpoint("GET", "/api/2/monitoring/ipd", "Get if IPD Monitoring is enabled")
SET_APP_MONITORING_ENABLED_1 = Endpoint("POST", "/api/2/monitoring/ipd", "Update IPD Monitoring status")
ARE_METRICS_EXPOSED = Endpoint("GET", "/api/2/monitoring/jmx/areMetricsExposed", "Check if JMX metrics are being ex...")
GET_AVAILABLE_METRICS = Endpoint("GET", "/api/2/monitoring/jmx/getAvailableMetrics", "Get the available JMX metrics")
START = Endpoint("POST", "/api/2/monitoring/jmx/startExposing", "Start exposing JMX metrics")
STOP = Endpoint("POST", "/api/2/monitoring/jmx/stopExposing", "Stop exposing JMX metrics")
GET_REINDEX_INFO = Endpoint("GET", "/api/2/reindex", "Get reindex information")
REINDEX = Endpoint("POST", "/api/2/reindex", "Start a reindex operation")
REINDEX_ISSUES = Endpoint("POST", "/api/2/reindex/issue", "Reindex individual issues")
GET_REINDEX_PROGRESS = Endpoint("GET", "/api/2/reindex/progress", "Get reindex progress")
PROCESS_REQUESTS = Endpoint("POST", "/api/2/reindex/request", "Execute pending reindex requests")
GET_PROGRESS_BULK = Endpoint("GET", "/api/2/reindex/request/bulk", "Get progress of multiple reindex requests")
GET_PROGRESS = Endpoint("GET", "/api/2/reindex/request/{requestId}", "Get progress of a single reindex request")
GET_UPGRADE_RESULT = Endpoint("GET", "/api/2/upgrade", "Get result of the last upgrade task")
RUN_UPGRADES_NOW = Endpoint("POST", "/api/2/upgrade", "Run pending upgrade tasks")

# --- Auth ---

GET_PASSWORD_POLICY = Endpoint("GET", "/api/2/password/policy", "Get current password policy requirements")
POLICY_CHECK_CREATE_USER = Endpoint("POST", "/api/2/password/policy/createUser", "Get reasons for password policy d...")
POLICY_CHECK_UPDATE_USER = Endpoint("POST", "/api/2/password/policy/updateUser", "Get reasons for password policy d...")
LOGOUT = Endpoint("DELETE", "/auth/1/session", "Delete current user session")
CURRENT_USER = Endpoint("GET", "/auth/1/session", "Get current user session information")
LOGIN = Endpoint("POST", "/auth/1/session", "Create new user session")
RELEASE = Endpoint("DELETE", "/auth/1/websudo", "Invalidate the current WebSudo session")
