# Do not edit this file directly. It has been autogenerated from
# atlassian\bitbucket\async_client.py
from __future__ import annotations

import httpx

from atlassian.core.auth import AuthBase, BasicAuth, TokenAuth
from atlassian.core.client import BaseClient

from .resources import (
    AdminResource,
    AuthenticationResource,
    BuildsResource,
    DashboardResource,
    JiraIntegrationResource,
    MarkupResource,
    MirroringResource,
    PermissionsResource,
    ProjectsResource,
    PullRequestsResource,
    RepositoriesResource,
    SecurityResource,
)


class BitBucketClient(BaseClient):
    def __init__(
        self,
        *,
        url: str,
        username: str | None = None,
        password: str | None = None,
        token: str | None = None,
        auth: AuthBase | None = None,
        timeout: float = 30.0,
        max_retries: int = 3,
        retry_backoff_factor: float = 0.5,
        verify_ssl: bool = True,
        transport: httpx.BaseTransport | None = None,
    ) -> None:
        resolved_auth = self._resolve_auth(
            username=username,
            password=password,
            token=token,
            auth=auth,
        )

        super().__init__(
            base_url=url,
            auth=resolved_auth,
            timeout=timeout,
            max_retries=max_retries,
            retry_backoff_factor=retry_backoff_factor,
            verify_ssl=verify_ssl,
            transport=transport,
        )

        self._projects: ProjectsResource | None = None
        self._repositories: RepositoriesResource | None = None
        self._pull_requests: PullRequestsResource | None = None
        self._authentication: AuthenticationResource | None = None
        self._builds: BuildsResource | None = None
        self._permissions: PermissionsResource | None = None
        self._security: SecurityResource | None = None
        self._admin: AdminResource | None = None
        self._dashboard: DashboardResource | None = None
        self._mirroring: MirroringResource | None = None
        self._jira_integration: JiraIntegrationResource | None = None
        self._markup: MarkupResource | None = None

    @staticmethod
    def _resolve_auth(
        *,
        username: str | None,
        password: str | None,
        token: str | None,
        auth: AuthBase | None,
    ) -> AuthBase | None:
        if auth is not None and any(value is not None for value in (username, password, token)):
            raise ValueError("Provide either auth or username/password/token, not both.")

        if token is not None and any(value is not None for value in (username, password)):
            raise ValueError("Token authentication cannot be combined with username/password.")

        if (username is None) != (password is None):
            raise ValueError("Both username and password must be provided together.")

        if auth is not None:
            return auth
        if token is not None:
            return TokenAuth(token)
        if username is not None and password is not None:
            return BasicAuth(username, password)
        return None

    @property
    def projects(self) -> ProjectsResource:
        if self._projects is None:
            self._projects = ProjectsResource(self)
        return self._projects

    @property
    def repositories(self) -> RepositoriesResource:
        if self._repositories is None:
            self._repositories = RepositoriesResource(self)
        return self._repositories

    @property
    def pull_requests(self) -> PullRequestsResource:
        if self._pull_requests is None:
            self._pull_requests = PullRequestsResource(self)
        return self._pull_requests

    @property
    def authentication(self) -> AuthenticationResource:
        if self._authentication is None:
            self._authentication = AuthenticationResource(self)
        return self._authentication

    @property
    def builds(self) -> BuildsResource:
        if self._builds is None:
            self._builds = BuildsResource(self)
        return self._builds

    @property
    def permissions(self) -> PermissionsResource:
        if self._permissions is None:
            self._permissions = PermissionsResource(self)
        return self._permissions

    @property
    def security(self) -> SecurityResource:
        if self._security is None:
            self._security = SecurityResource(self)
        return self._security

    @property
    def admin(self) -> AdminResource:
        if self._admin is None:
            self._admin = AdminResource(self)
        return self._admin

    @property
    def dashboard(self) -> DashboardResource:
        if self._dashboard is None:
            self._dashboard = DashboardResource(self)
        return self._dashboard

    @property
    def mirroring(self) -> MirroringResource:
        if self._mirroring is None:
            self._mirroring = MirroringResource(self)
        return self._mirroring

    @property
    def jira_integration(self) -> JiraIntegrationResource:
        if self._jira_integration is None:
            self._jira_integration = JiraIntegrationResource(self)
        return self._jira_integration

    @property
    def markup(self) -> MarkupResource:
        if self._markup is None:
            self._markup = MarkupResource(self)
        return self._markup
