# Do not edit this file directly. It has been autogenerated from
# atlassian\confluence\async_client.py
from __future__ import annotations

import httpx

from atlassian.core.auth import AuthBase, BasicAuth, TokenAuth
from atlassian.core.client import BaseClient

from .resources import (
    AccessModeResource,
    AdminResource,
    AttachmentsResource,
    BackupRestoreResource,
    CategoryResource,
    ChildContentResource,
    ContentDescendantResource,
    ContentLabelsResource,
    ContentPropertyResource,
    ContentResource,
    ContentRestrictionsResource,
    GlobalColorSchemeResource,
    GlobalPermissionsResource,
    GroupResource,
    LabelResource,
    LongTaskResource,
    SearchResource,
    ServerInfoResource,
    SpaceColorSchemeResource,
    SpaceLabelResource,
    SpacePermissionsResource,
    SpacePropertyResource,
    SpaceResource,
    UserResource,
    UserWatchResource,
    WebhooksResource,
)


class ConfluenceContentGroup(ContentResource):
    def __init__(self, owner: ConfluenceClient) -> None:
        super().__init__(owner)
        self._owner = owner

    @property
    def labels(self) -> ContentLabelsResource:
        return self._owner.content_labels

    @property
    def props(self) -> ContentPropertyResource:
        return self._owner.content_property

    @property
    def restrictions(self) -> ContentRestrictionsResource:
        return self._owner.content_restrictions

    @property
    def descendant(self) -> ContentDescendantResource:
        return self._owner.content_descendant

    @property
    def child(self) -> ChildContentResource:
        return self._owner.child_content

    @property
    def children(self) -> ChildContentResource:
        return self._owner.child_content

    @property
    def attachments(self) -> AttachmentsResource:
        return self._owner.attachments


class ConfluenceSpaceGroup(SpaceResource):
    def __init__(self, owner: ConfluenceClient) -> None:
        super().__init__(owner)
        self._owner = owner

    @property
    def labels(self) -> SpaceLabelResource:
        return self._owner.space_label

    @property
    def permissions(self) -> SpacePermissionsResource:
        return self._owner.space_permissions

    @property
    def props(self) -> SpacePropertyResource:
        return self._owner.space_property

    @property
    def color_scheme(self) -> SpaceColorSchemeResource:
        return self._owner.space_color_scheme

    @property
    def colors(self) -> SpaceColorSchemeResource:
        return self._owner.space_color_scheme


class ConfluenceClient(BaseClient):
    def __init__(
        self,
        *,
        url: str,
        username: str | None = None,
        password: str | None = None,
        token: str | None = None,
        auth: AuthBase | None = None,
        timeout: float = 30.0,
        max_retries: int = 3,
        retry_backoff_factor: float = 0.5,
        verify_ssl: bool = True,
        transport: httpx.BaseTransport | None = None,
    ) -> None:
        normalized_url = self._normalize_url(url)
        resolved_auth = self._resolve_auth(
            username=username,
            password=password,
            token=token,
            auth=auth,
        )

        super().__init__(
            base_url=normalized_url,
            auth=resolved_auth,
            timeout=timeout,
            max_retries=max_retries,
            retry_backoff_factor=retry_backoff_factor,
            verify_ssl=verify_ssl,
            transport=transport,
        )

        self._content: ConfluenceContentGroup | None = None
        self._content_labels: ContentLabelsResource | None = None
        self._content_property: ContentPropertyResource | None = None
        self._content_restrictions: ContentRestrictionsResource | None = None
        self._content_descendant: ContentDescendantResource | None = None
        self._child_content: ChildContentResource | None = None
        self._attachments: AttachmentsResource | None = None
        self._space: ConfluenceSpaceGroup | None = None
        self._space_label: SpaceLabelResource | None = None
        self._space_permissions: SpacePermissionsResource | None = None
        self._space_property: SpacePropertyResource | None = None
        self._space_color_scheme: SpaceColorSchemeResource | None = None
        self._group: GroupResource | None = None
        self._user: UserResource | None = None
        self._user_watch: UserWatchResource | None = None
        self._search: SearchResource | None = None
        self._label: LabelResource | None = None
        self._long_task: LongTaskResource | None = None
        self._backup_restore: BackupRestoreResource | None = None
        self._webhooks: WebhooksResource | None = None
        self._global_permissions: GlobalPermissionsResource | None = None
        self._global_color_scheme: GlobalColorSchemeResource | None = None
        self._category: CategoryResource | None = None
        self._access_mode: AccessModeResource | None = None
        self._server_info: ServerInfoResource | None = None
        self._admin: AdminResource | None = None

    @staticmethod
    def _normalize_url(url: str) -> str:
        stripped = url.rstrip("/")
        if stripped.endswith("/rest"):
            return stripped
        return f"{stripped}/rest"

    @staticmethod
    def _resolve_auth(
        *,
        username: str | None,
        password: str | None,
        token: str | None,
        auth: AuthBase | None,
    ) -> AuthBase | None:
        if auth is not None and any(value is not None for value in (username, password, token)):
            raise ValueError("Provide either auth or username/password/token, not both.")

        if token is not None and any(value is not None for value in (username, password)):
            raise ValueError("Token authentication cannot be combined with username/password.")

        if (username is None) != (password is None):
            raise ValueError("Both username and password must be provided together.")

        if auth is not None:
            return auth
        if token is not None:
            return TokenAuth(token)
        if username is not None and password is not None:
            return BasicAuth(username, password)
        return None

    @property
    def content(self) -> ConfluenceContentGroup:
        if self._content is None:
            self._content = ConfluenceContentGroup(self)
        return self._content

    @property
    def content_labels(self) -> ContentLabelsResource:
        if self._content_labels is None:
            self._content_labels = ContentLabelsResource(self)
        return self._content_labels

    @property
    def content_property(self) -> ContentPropertyResource:
        if self._content_property is None:
            self._content_property = ContentPropertyResource(self)
        return self._content_property

    @property
    def content_restrictions(self) -> ContentRestrictionsResource:
        if self._content_restrictions is None:
            self._content_restrictions = ContentRestrictionsResource(self)
        return self._content_restrictions

    @property
    def content_descendant(self) -> ContentDescendantResource:
        if self._content_descendant is None:
            self._content_descendant = ContentDescendantResource(self)
        return self._content_descendant

    @property
    def child_content(self) -> ChildContentResource:
        if self._child_content is None:
            self._child_content = ChildContentResource(self)
        return self._child_content

    @property
    def attachments(self) -> AttachmentsResource:
        if self._attachments is None:
            self._attachments = AttachmentsResource(self)
        return self._attachments

    @property
    def space(self) -> ConfluenceSpaceGroup:
        if self._space is None:
            self._space = ConfluenceSpaceGroup(self)
        return self._space

    @property
    def space_label(self) -> SpaceLabelResource:
        if self._space_label is None:
            self._space_label = SpaceLabelResource(self)
        return self._space_label

    @property
    def space_permissions(self) -> SpacePermissionsResource:
        if self._space_permissions is None:
            self._space_permissions = SpacePermissionsResource(self)
        return self._space_permissions

    @property
    def space_property(self) -> SpacePropertyResource:
        if self._space_property is None:
            self._space_property = SpacePropertyResource(self)
        return self._space_property

    @property
    def space_color_scheme(self) -> SpaceColorSchemeResource:
        if self._space_color_scheme is None:
            self._space_color_scheme = SpaceColorSchemeResource(self)
        return self._space_color_scheme

    @property
    def group(self) -> GroupResource:
        if self._group is None:
            self._group = GroupResource(self)
        return self._group

    @property
    def user(self) -> UserResource:
        if self._user is None:
            self._user = UserResource(self)
        return self._user

    @property
    def user_watch(self) -> UserWatchResource:
        if self._user_watch is None:
            self._user_watch = UserWatchResource(self)
        return self._user_watch

    @property
    def search(self) -> SearchResource:
        if self._search is None:
            self._search = SearchResource(self)
        return self._search

    @property
    def label(self) -> LabelResource:
        if self._label is None:
            self._label = LabelResource(self)
        return self._label

    @property
    def long_task(self) -> LongTaskResource:
        if self._long_task is None:
            self._long_task = LongTaskResource(self)
        return self._long_task

    @property
    def tasks(self) -> LongTaskResource:
        return self.long_task

    @property
    def backup_restore(self) -> BackupRestoreResource:
        if self._backup_restore is None:
            self._backup_restore = BackupRestoreResource(self)
        return self._backup_restore

    @property
    def backup(self) -> BackupRestoreResource:
        return self.backup_restore

    @property
    def webhooks(self) -> WebhooksResource:
        if self._webhooks is None:
            self._webhooks = WebhooksResource(self)
        return self._webhooks

    @property
    def global_permissions(self) -> GlobalPermissionsResource:
        if self._global_permissions is None:
            self._global_permissions = GlobalPermissionsResource(self)
        return self._global_permissions

    @property
    def global_color_scheme(self) -> GlobalColorSchemeResource:
        if self._global_color_scheme is None:
            self._global_color_scheme = GlobalColorSchemeResource(self)
        return self._global_color_scheme

    @property
    def colors(self) -> GlobalColorSchemeResource:
        return self.global_color_scheme

    @property
    def category(self) -> CategoryResource:
        if self._category is None:
            self._category = CategoryResource(self)
        return self._category

    @property
    def access_mode(self) -> AccessModeResource:
        if self._access_mode is None:
            self._access_mode = AccessModeResource(self)
        return self._access_mode

    @property
    def server_info(self) -> ServerInfoResource:
        if self._server_info is None:
            self._server_info = ServerInfoResource(self)
        return self._server_info

    @property
    def info(self) -> ServerInfoResource:
        return self.server_info

    @property
    def admin(self) -> AdminResource:
        if self._admin is None:
            self._admin = AdminResource(self)
        return self._admin
