# Do not edit this file directly. It has been autogenerated from
# atlassian\confluence\async_resources.py
"""Confluence Data Center resource classes.

Auto-generated scaffold from the OpenAPI spec. Safe to hand-edit.
"""

from __future__ import annotations

from atlassian.confluence.resource import ConfluenceResource
from atlassian.core.pagination import PageIterator

from .endpoints import (
    ADD,
    ADD_CONTENT_WATCHER,
    ADD_LABELS,
    ADD_SPACE_WATCH,
    ARCHIVE,
    BY_OPERATION,
    CANCEL_ALL_QUEUED_JOBS,
    CANCEL_JOB,
    CHANGE_PASSWORD,
    CHANGE_PASSWORD_1,
    CHILDREN,
    CHILDREN_OF_TYPE,
    COMMENTS_OF_CONTENT,
    CONTENTS,
    CONTENTS_WITH_TYPE,
    CONTENTS_WITH_TYPE_1,
    CONVERT,
    CREATE,
    CREATE_1,
    CREATE_2,
    CREATE_3,
    CREATE_4,
    CREATE_ATTACHMENTS,
    CREATE_CONTENT,
    CREATE_PERSONAL_SPACE_1,
    CREATE_PRIVATE_SPACE,
    CREATE_SITE_BACKUP_JOB,
    CREATE_SITE_RESTORE_JOB,
    CREATE_SITE_RESTORE_JOB_FOR_UPLOADED_BACKUP_FILE,
    CREATE_SPACE,
    CREATE_SPACE_BACKUP_JOB,
    CREATE_SPACE_RESTORE_JOB,
    CREATE_SPACE_RESTORE_JOB_FOR_UPLOADED_BACKUP_FILE,
    CREATE_USER,
    CREATE_WEBHOOK,
    DELETE,
    DELETE_1,
    DELETE_2,
    DELETE_3,
    DELETE_4,
    DELETE_5,
    DELETE_6,
    DELETE_CONTENT_HISTORY,
    DELETE_LABEL,
    DELETE_LABEL_WITH_QUERY_PARAM,
    DELETE_WEBHOOK,
    DESCENDANTS,
    DESCENDANTS_OF_TYPE,
    DISABLE,
    DOWNLOAD_BACKUP_FILE,
    ENABLE,
    FIND_ALL,
    FIND_BY_KEY,
    FIND_JOBS,
    FIND_WEBHOOKS,
    FOR_OPERATION,
    GET,
    GET_1,
    GET_ACCESS_MODE_STATUS,
    GET_ALL_GLOBAL_PERMISSIONS,
    GET_ALL_SPACE_PERMISSIONS,
    GET_ANONYMOUS,
    GET_ATTACHMENTS,
    GET_AUDIT_RECORDS,
    GET_COLOR_SCHEME_TYPE,
    GET_CONTENT,
    GET_CONTENT_BY_ID,
    GET_CURRENT,
    GET_DEFAULT_COLOR_SCHEME,
    GET_FILES,
    GET_GLOBAL_COLOR_SCHEME,
    GET_GROUP,
    GET_GROUPS,
    GET_GROUPS_1,
    GET_HISTORY,
    GET_JOB,
    GET_LATEST_INVOCATION,
    GET_MACRO_BODY_BY_HASH,
    GET_MACRO_BODY_BY_MACRO_ID,
    GET_MEMBERS,
    GET_NESTED_GROUP_MEMBERS,
    GET_PERMISSIONS_GRANTED_TO_ANONYMOUS_USERS,
    GET_PERMISSIONS_GRANTED_TO_ANONYMOUS_USERS_1,
    GET_PERMISSIONS_GRANTED_TO_GROUP,
    GET_PERMISSIONS_GRANTED_TO_GROUP_1,
    GET_PERMISSIONS_GRANTED_TO_UNLICENSED_USERS,
    GET_PERMISSIONS_GRANTED_TO_USER,
    GET_PERMISSIONS_GRANTED_TO_USER_1,
    GET_SPACE_COLOR_SCHEME,
    GET_STATISTICS,
    GET_STATISTICS_SUMMARY,
    GET_TASK,
    GET_TASKS,
    GET_USER,
    GET_USERS,
    GET_WEBHOOK,
    GRANT_PERMISSIONS_TO_ANONYMOUS_USERS,
    GRANT_PERMISSIONS_TO_ANONYMOUS_USERS_1,
    GRANT_PERMISSIONS_TO_GROUP,
    GRANT_PERMISSIONS_TO_GROUP_1,
    GRANT_PERMISSIONS_TO_UNLICENSED_USERS,
    GRANT_PERMISSIONS_TO_USER,
    GRANT_PERMISSIONS_TO_USER_1,
    INDEX,
    INDEX_1,
    INDEX_2,
    INDEX_3,
    INDEX_4,
    IS_WATCHING_CONTENT,
    IS_WATCHING_SPACE,
    LABELS,
    LABELS_1,
    MOVE,
    POPULAR,
    POPULAR_1,
    PUBLISH_LEGACY_DRAFT,
    PUBLISH_SHARED_DRAFT,
    RECENT,
    RECENT_1,
    RELATED,
    RELATED_1,
    RELEVANT_VIEW_RESTRICTIONS,
    REMOVE_ATTACHMENT,
    REMOVE_ATTACHMENT_VERSION,
    REMOVE_CATEGORY,
    REMOVE_CONTENT_WATCHER,
    REMOVE_SPACE_WATCH,
    RESET_GLOBAL_COLOR_SCHEME,
    RESET_SPACE_COLOR_SCHEME,
    RESTORE,
    REVOKE_PERMISSIONS_FROM_ANONYMOUS_USER,
    REVOKE_PERMISSIONS_FROM_ANONYMOUS_USERS,
    REVOKE_PERMISSIONS_FROM_GROUP,
    REVOKE_PERMISSIONS_FROM_GROUP_1,
    REVOKE_PERMISSIONS_FROM_UNLICENSED_USERS,
    REVOKE_PERMISSIONS_FROM_USER,
    REVOKE_PERMISSIONS_FROM_USER_1,
    SCAN_CONTENT,
    SEARCH,
    SEARCH_1,
    SET_PERMISSIONS,
    SET_PERMISSIONS_1,
    SPACE,
    SPACES,
    TEST_WEBHOOK,
    TRASH,
    UPDATE,
    UPDATE_1,
    UPDATE_2,
    UPDATE_3,
    UPDATE_4,
    UPDATE_5,
    UPDATE_COLOR_SCHEME,
    UPDATE_COLOR_SCHEME_TYPE,
    UPDATE_DATA,
    UPDATE_RESTRICTIONS,
    UPDATE_SPACE_COLOR_SCHEME,
    UPDATE_USER,
    UPDATE_USER_1,
    UPDATE_WEBHOOK,
)
from .models import (
    ColorSchemeThemeBasedModel,
    Content,
    ContentBody,
    ContentWatch,
    Credentials,
    DetailedInvocation,
    ExampleMultipartFormData,
    FileInfo,
    GlobalPermission,
    Group,
    History,
    InstanceMetrics,
    JobDetails,
    JsonContentProperty,
    JsonSpaceProperty,
    Label,
    LongTaskStatus,
    LongTaskSubmission,
    MacroInstance,
    MockAttachmentRequest,
    MockRestrictionsResponse,
    OperationRestriction,
    PasswordChangeDetails,
    Person,
    PersonalSpaceDetailsForCreation,
    RestInvocationHistory,
    RestWebhook,
    SearchResult,
    ServerInformation,
    SiteBackupJobDetails,
    SiteBackupSettings,
    SiteRestoreJobDetails,
    SiteRestoreSettings,
    Space,
    SpaceBackupJobDetails,
    SpaceBackupSettings,
    SpaceColorSchemeTypeModel,
    SpacePermission,
    SpaceRestoreJobDetails,
    SpaceRestoreSettings,
    SpaceWatch,
    User,
    UserDetailsForCreation,
    UserDetailsForUpdate,
    UserKey,
    Webhook,
)


class ContentResource(ConfluenceResource):
    def get_content(
        self,
        *,
        space_key: str | None = None,
        expand: str | None = None,
        posting_day: str | None = None,
        ids: str | None = None,
        title: str | None = None,
        type_: str | None = None,
        status: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Content]:
        """Get content"""
        return self._get_paged(
            GET_CONTENT.path,
            params={
                "spaceKey": space_key,
                "expand": expand,
                "postingDay": posting_day,
                "ids": ids,
                "title": title,
                "type": type_,
                "status": status,
            },
            model=Content,
            start=start,
            limit=limit,
        )

    def create_content(self, body: Content, *, expand: str | None = None, status: str | None = None) -> Content:
        """Create content"""
        return self._post(
            CREATE_CONTENT.path,
            params={"expand": expand, "status": status},
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=Content,
        )

    def publish_legacy_draft(
        self,
        draft_id: str,
        body: Content,
        *,
        expand: str | None = None,
        status: str | None = None,
    ) -> Content:
        """Publish legacy draft"""
        return self._post(
            PUBLISH_LEGACY_DRAFT.path.format(draftId=draft_id),
            params={"expand": expand, "status": status},
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=Content,
        )

    def publish_shared_draft(
        self,
        draft_id: str,
        body: Content,
        *,
        expand: str | None = None,
        status: str | None = None,
    ) -> Content:
        """Publish shared draft"""
        return self._put(
            PUBLISH_SHARED_DRAFT.path.format(draftId=draft_id),
            params={"expand": expand, "status": status},
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=Content,
        )

    def scan_content(
        self,
        *,
        cursor: str | None = None,
        space_key: str | None = None,
        expand: str | None = None,
        limit: str | None = None,
        type_: str | None = None,
        status: str | None = None,
    ) -> None:
        """Scan content by space key"""
        return self._get(
            SCAN_CONTENT.path,
            params={
                "cursor": cursor,
                "spaceKey": space_key,
                "expand": expand,
                "limit": limit,
                "type": type_,
                "status": status,
            },
        )

    def search(
        self,
        *,
        cqlcontext: str | None = None,
        expand: str | None = None,
        cql: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Content]:
        """Search content using CQL"""
        return self._get_paged(
            SEARCH.path,
            params={"cqlcontext": cqlcontext, "expand": expand, "cql": cql},
            model=Content,
            start=start,
            limit=limit,
        )

    def update_2(
        self,
        content_id: str,
        body: Content,
        *,
        async_reconciliation: bool | None = False,
        conflict_policy: str | None = None,
        status: str | None = None,
    ) -> Content:
        """Update content"""
        return self._put(
            UPDATE_2.path.format(contentId=content_id),
            params={"asyncReconciliation": async_reconciliation, "conflictPolicy": conflict_policy, "status": status},
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=Content,
        )

    def index(self, content_id: str, *, start: int = 0, limit: int = 25) -> PageIterator[User]:
        """Fetch users watching a given content"""
        return self._get_paged(INDEX.path.format(contentId=content_id), model=User, start=start, limit=limit)

    def delete_3(self, id: str, *, status: str | None = None) -> None:
        """Delete content"""
        return self._delete(DELETE_3.path.format(id=id), params={"status": status})

    def get_content_by_id(
        self,
        id: str,
        *,
        expand: str | None = None,
        version: str | None = None,
        status: str | None = None,
    ) -> Content:
        """Get content by ID"""
        return self._get(
            GET_CONTENT_BY_ID.path.format(id=id),
            params={"expand": expand, "version": version, "status": status},
            model=Content,
        )

    def get_history(self, id: str, *, expand: str | None = None) -> History:
        """Get history of content"""
        return self._get(GET_HISTORY.path.format(id=id), params={"expand": expand}, model=History)

    def get_macro_body_by_hash(self, id: str, version: str, hash: str) -> MacroInstance:
        """Get macro body by hash"""
        return self._get(
            GET_MACRO_BODY_BY_HASH.path.format(id=id, version=version, hash=hash),
            model=MacroInstance,
        )

    def get_macro_body_by_macro_id(self, macro_id: str, id: str, version: str) -> MacroInstance:
        """Get macro body by macro ID"""
        return self._get(
            GET_MACRO_BODY_BY_MACRO_ID.path.format(macroId=macro_id, id=id, version=version),
            model=MacroInstance,
        )

    def delete_content_history(self, id: str, version_number: str) -> None:
        """Delete content history"""
        return self._delete(DELETE_CONTENT_HISTORY.path.format(id=id, versionNumber=version_number))

    def convert(self, to: str, body: ContentBody, *, expand: str | None = None) -> ContentBody:
        """Convert body representation"""
        return self._post(
            CONVERT.path.format(to=to),
            params={"expand": expand},
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=ContentBody,
        )


class ContentLabelsResource(ConfluenceResource):
    def delete_label_with_query_param(self, id: str, *, name: str | None = None) -> None:
        """Delete label with query param"""
        return self._delete(DELETE_LABEL_WITH_QUERY_PARAM.path.format(id=id), params={"name": name})

    def labels(
        self,
        id: str,
        *,
        prefix: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Label]:
        """Get labels"""
        return self._get_paged(
            LABELS.path.format(id=id),
            params={"prefix": prefix},
            model=Label,
            start=start,
            limit=limit,
        )

    def add_labels(self, id: str, body: Label, *, start: int = 0, limit: int = 25) -> PageIterator[Label]:
        """Add Labels"""
        return self._request_paged(
            "POST",
            ADD_LABELS.path.format(id=id),
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=Label,
            start=start,
            limit=limit,
        )

    def delete_label(self, id: str, label: str) -> None:
        """Delete label"""
        return self._delete(DELETE_LABEL.path.format(id=id, label=label))


class ContentPropertyResource(ConfluenceResource):
    def find_all(
        self,
        id: str,
        *,
        expand: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[JsonContentProperty]:
        """Find all content properties"""
        return self._get_paged(
            FIND_ALL.path.format(id=id),
            params={"expand": expand},
            model=JsonContentProperty,
            start=start,
            limit=limit,
        )

    def create_1(self, id: str, body: JsonContentProperty) -> JsonContentProperty:
        """Create a content property"""
        return self._post(
            CREATE_1.path.format(id=id),
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=JsonContentProperty,
        )

    def delete_2(self, id: str, key: str) -> None:
        """Delete content property"""
        return self._delete(DELETE_2.path.format(id=id, key=key))

    def find_by_key(
        self,
        id: str,
        key: str,
        *,
        expand: str | None = None,
        limit: str | None = None,
    ) -> JsonContentProperty:
        """Find content property by key"""
        return self._get(
            FIND_BY_KEY.path.format(id=id, key=key),
            params={"expand": expand, "limit": limit},
            model=JsonContentProperty,
        )

    def create_2(self, id: str, key: str, body: JsonContentProperty) -> None:
        """POST /rest/api/content/{id}/property/{key}"""
        return self._post(
            CREATE_2.path.format(id=id, key=key),
            json=body.model_dump(by_alias=True, exclude_none=True),
        )

    def update_1(
        self,
        id: str,
        key: str,
        body: JsonContentProperty,
        *,
        expand: str | None = None,
    ) -> JsonContentProperty:
        """Update content property"""
        return self._put(
            UPDATE_1.path.format(id=id, key=key),
            params={"expand": expand},
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=JsonContentProperty,
        )


class ContentRestrictionsResource(ConfluenceResource):
    def update_restrictions(
        self,
        id: str,
        *,
        expand: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[OperationRestriction]:
        """Update restrictions"""
        return self._request_paged(
            "PUT",
            UPDATE_RESTRICTIONS.path.format(id=id),
            params={"expand": expand},
            model=OperationRestriction,
            start=start,
            limit=limit,
        )

    def by_operation(self, id: str, *, expand: str | None = None) -> MockRestrictionsResponse:
        """Get all restrictions by Operation"""
        return self._get(
            BY_OPERATION.path.format(id=id),
            params={"expand": expand},
            model=MockRestrictionsResponse,
        )

    def for_operation(
        self,
        operation_key: str,
        id: str,
        *,
        expand: str | None = None,
        limit: str | None = None,
        start: str | None = None,
    ) -> OperationRestriction:
        """Get all restrictions for given operation"""
        return self._get(
            FOR_OPERATION.path.format(operationKey=operation_key, id=id),
            params={"expand": expand, "limit": limit, "start": start},
            model=OperationRestriction,
        )

    def relevant_view_restrictions(
        self,
        id: str,
        *,
        expand: str | None = None,
        limit: str | None = None,
        start: str | None = None,
    ) -> MockRestrictionsResponse:
        """Get all view restriction both direct and inherited."""
        return self._get(
            RELEVANT_VIEW_RESTRICTIONS.path.format(id=id),
            params={"expand": expand, "limit": limit, "start": start},
            model=MockRestrictionsResponse,
        )


class ContentDescendantResource(ConfluenceResource):
    def descendants(
        self,
        id: str,
        *,
        expand: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Content]:
        """Get Descendants"""
        return self._get_paged(
            DESCENDANTS.path.format(id=id),
            params={"expand": expand},
            model=Content,
            start=start,
            limit=limit,
        )

    def descendants_of_type(
        self,
        id: str,
        type_: str,
        *,
        expand: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Content]:
        """Get descendants of type"""
        return self._get_paged(
            DESCENDANTS_OF_TYPE.path.format(id=id, type=type_),
            params={"expand": expand},
            model=Content,
            start=start,
            limit=limit,
        )


class ChildContentResource(ConfluenceResource):
    def children(
        self,
        id: str,
        *,
        expand: str | None = None,
        parent_version: int | None = 0,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Content]:
        """Get children of content"""
        return self._get_paged(
            CHILDREN.path.format(id=id),
            params={"expand": expand, "parentVersion": parent_version},
            model=Content,
            start=start,
            limit=limit,
        )

    def comments_of_content(
        self,
        id: str,
        *,
        expand: str | None = None,
        depth: str | None = None,
        location: str | None = None,
        parent_version: int | None = 0,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Content]:
        """Get comments of content"""
        return self._get_paged(
            COMMENTS_OF_CONTENT.path.format(id=id),
            params={"expand": expand, "depth": depth, "location": location, "parentVersion": parent_version},
            model=Content,
            start=start,
            limit=limit,
        )

    def children_of_type(
        self,
        id: str,
        type_: str,
        *,
        expand: str | None = None,
        parent_version: int | None = 0,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Content]:
        """Get children of content by type"""
        return self._get_paged(
            CHILDREN_OF_TYPE.path.format(id=id, type=type_),
            params={"expand": expand, "parentVersion": parent_version},
            model=Content,
            start=start,
            limit=limit,
        )


class AttachmentsResource(ConfluenceResource):
    def get_attachments(
        self,
        id: str,
        *,
        expand: str | None = None,
        filename: str | None = None,
        media_type: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Content]:
        """Get attachment"""
        return self._get_paged(
            GET_ATTACHMENTS.path.format(id=id),
            params={"expand": expand, "filename": filename, "mediaType": media_type},
            model=Content,
            start=start,
            limit=limit,
        )

    def create_attachments(
        self,
        id: str,
        body: MockAttachmentRequest,
        *,
        expand: str | None = None,
        allow_duplicated: str | None = None,
        status: str | None = None,
    ) -> Content:
        """Create attachments"""
        return self._post(
            CREATE_ATTACHMENTS.path.format(id=id),
            params={"expand": expand, "allowDuplicated": allow_duplicated, "status": status},
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=Content,
        )

    def remove_attachment(self, attachment_id: str, id: str) -> None:
        """Remove attachment"""
        return self._delete(REMOVE_ATTACHMENT.path.format(attachmentId=attachment_id, id=id))

    def update(self, attachment_id: str, id: str, body: Content) -> Content:
        """Update non-binary data of an Attachment"""
        return self._put(
            UPDATE.path.format(attachmentId=attachment_id, id=id),
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=Content,
        )

    def update_data(self, attachment_id: str, id: str, body: MockAttachmentRequest) -> Content:
        """Update binary data of an attachment"""
        return self._post(
            UPDATE_DATA.path.format(attachmentId=attachment_id, id=id),
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=Content,
        )

    def move(
        self,
        attachment_id: str,
        id: str,
        *,
        new_name: str | None = None,
        new_content_id: str | None = None,
    ) -> None:
        """Move attachment"""
        return self._post(
            MOVE.path.format(attachmentId=attachment_id, id=id),
            params={"newName": new_name, "newContentId": new_content_id},
        )

    def remove_attachment_version(self, attachment_id: str, id: str, version: int) -> None:
        """Remove attachment version"""
        return self._delete(
            REMOVE_ATTACHMENT_VERSION.path.format(attachmentId=attachment_id, id=id, version=version),
        )


class SpaceResource(ConfluenceResource):
    def spaces(
        self,
        *,
        space_key_single: str | None = None,
        label: str | None = None,
        favourite: str | None = None,
        type_: str | None = None,
        space_key: str | None = None,
        space_id: list[str] | None = None,
        expand: str | None = None,
        has_retention_policy: str | None = None,
        space_keys: str | None = None,
        content_label: str | None = None,
        space_ids: str | None = None,
        status: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Space]:
        """Get spaces by key"""
        return self._get_paged(
            SPACES.path,
            params={
                "spaceKeySingle": space_key_single,
                "label": label,
                "favourite": favourite,
                "type": type_,
                "spaceKey": space_key,
                "spaceId": space_id,
                "expand": expand,
                "hasRetentionPolicy": has_retention_policy,
                "spaceKeys": space_keys,
                "contentLabel": content_label,
                "spaceIds": space_ids,
                "status": status,
            },
            model=Space,
            start=start,
            limit=limit,
        )

    def create_space(self, body: Space) -> Space:
        """Creates a new Space."""
        return self._post(CREATE_SPACE.path, json=body.model_dump(by_alias=True, exclude_none=True), model=Space)

    def create_private_space(self, body: Space) -> Space:
        """Create private space"""
        return self._post(
            CREATE_PRIVATE_SPACE.path,
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=Space,
        )

    def create_personal_space_1(self, body: PersonalSpaceDetailsForCreation) -> Space:
        """Creates the personal Space for self."""
        return self._post(
            CREATE_PERSONAL_SPACE_1.path,
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=Space,
        )

    def delete_5(self, space_key: str) -> LongTaskSubmission:
        """Delete Space"""
        return self._delete(DELETE_5.path.format(spaceKey=space_key), model=LongTaskSubmission)

    def space(self, space_key: str, *, expand: str | None = None) -> Space:
        """Get space"""
        return self._get(SPACE.path.format(spaceKey=space_key), params={"expand": expand}, model=Space)

    def update_4(self, space_key: str, body: Space) -> Space:
        """Update Space"""
        return self._put(
            UPDATE_4.path.format(spaceKey=space_key),
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=Space,
        )

    def archive(self, space_key: str) -> None:
        """Archive space"""
        return self._put(ARCHIVE.path.format(spaceKey=space_key))

    def contents(
        self,
        space_key: str,
        *,
        expand: str | None = None,
        depth: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Content]:
        """Get contents in space"""
        return self._get_paged(
            CONTENTS.path.format(spaceKey=space_key),
            params={"expand": expand, "depth": depth},
            model=Content,
            start=start,
            limit=limit,
        )

    def contents_with_type_1(
        self,
        space_key: str,
        type_: str,
        *,
        expand: str | None = None,
        depth: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Content]:
        """Get contents by type"""
        return self._get_paged(
            CONTENTS_WITH_TYPE_1.path.format(spaceKey=space_key, type=type_),
            params={"expand": expand, "depth": depth},
            model=Content,
            start=start,
            limit=limit,
        )

    def restore(self, space_key: str) -> None:
        """Restore space"""
        return self._put(RESTORE.path.format(spaceKey=space_key))

    def trash(self, space_key: str) -> None:
        """Remove all trash contents"""
        return self._delete(TRASH.path.format(spaceKey=space_key))

    def contents_with_type(
        self,
        space_key: str,
        *,
        cursor: str | None = None,
        expand: str | None = None,
        limit: str | None = None,
    ) -> None:
        """Get trash contents of space"""
        return self._get(
            CONTENTS_WITH_TYPE.path.format(spaceKey=space_key),
            params={"cursor": cursor, "expand": expand, "limit": limit},
        )

    def index_4(self, space_key: str, *, start: int = 0, limit: int = 25) -> PageIterator[User]:
        """Fetch users watching space"""
        return self._get_paged(INDEX_4.path.format(spaceKey=space_key), model=User, start=start, limit=limit)


class SpaceLabelResource(ConfluenceResource):
    def index_3(self, space_key: str, *, start: int = 0, limit: int = 25) -> PageIterator[Label]:
        """Fetch all labels"""
        return self._get_paged(INDEX_3.path.format(spaceKey=space_key), model=Label, start=start, limit=limit)

    def popular_1(self, space_key: str, *, start: int = 0, limit: int = 25) -> PageIterator[Label]:
        """Get popular labels"""
        return self._get_paged(POPULAR_1.path.format(spaceKey=space_key), model=Label, start=start, limit=limit)

    def recent_1(self, space_key: str, *, start: int = 0, limit: int = 25) -> PageIterator[Label]:
        """Get recent labels"""
        return self._get_paged(RECENT_1.path.format(spaceKey=space_key), model=Label, start=start, limit=limit)

    def related_1(
        self,
        space_key: str,
        label_name: str,
        *,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Label]:
        """Get related labels"""
        return self._get_paged(
            RELATED_1.path.format(spaceKey=space_key, labelName=label_name),
            model=Label,
            start=start,
            limit=limit,
        )


class SpacePermissionsResource(ConfluenceResource):
    def get_all_space_permissions(self, space_key: str) -> SpacePermission:
        """Get all space permissions"""
        return self._get(GET_ALL_SPACE_PERMISSIONS.path.format(spaceKey=space_key), model=SpacePermission)

    def set_permissions_1(self, space_key: str) -> None:
        """Set permissions to multiple users/groups/anonymous user in the given space"""
        return self._post(SET_PERMISSIONS_1.path.format(spaceKey=space_key))

    def get_permissions_granted_to_anonymous_users_1(self, space_key: str) -> SpacePermission:
        """Gets the permissions granted to an anonymous user in a space"""
        return self._get(
            GET_PERMISSIONS_GRANTED_TO_ANONYMOUS_USERS_1.path.format(spaceKey=space_key),
            model=SpacePermission,
        )

    def grant_permissions_to_anonymous_users_1(self, space_key: str) -> None:
        """Grants space permissions to anonymous user"""
        return self._put(GRANT_PERMISSIONS_TO_ANONYMOUS_USERS_1.path.format(spaceKey=space_key))

    def revoke_permissions_from_anonymous_user(self, space_key: str) -> None:
        """Revoke space permissions from anonymous user"""
        return self._put(REVOKE_PERMISSIONS_FROM_ANONYMOUS_USER.path.format(spaceKey=space_key))

    def get_permissions_granted_to_group_1(self, space_key: str, group_name: str) -> SpacePermission:
        """Gets the permissions granted to a group in a space"""
        return self._get(
            GET_PERMISSIONS_GRANTED_TO_GROUP_1.path.format(spaceKey=space_key, groupName=group_name),
            model=SpacePermission,
        )

    def grant_permissions_to_group_1(self, space_key: str, group_name: str) -> None:
        """Grants space permissions to a group"""
        return self._put(GRANT_PERMISSIONS_TO_GROUP_1.path.format(spaceKey=space_key, groupName=group_name))

    def revoke_permissions_from_group_1(self, space_key: str, group_name: str) -> None:
        """Revoke space permissions from a group"""
        return self._put(REVOKE_PERMISSIONS_FROM_GROUP_1.path.format(spaceKey=space_key, groupName=group_name))

    def get_permissions_granted_to_user_1(self, space_key: str, user_key: str) -> SpacePermission:
        """Gets the permissions granted to a user in a space"""
        return self._get(
            GET_PERMISSIONS_GRANTED_TO_USER_1.path.format(spaceKey=space_key, userKey=user_key),
            model=SpacePermission,
        )

    def grant_permissions_to_user_1(self, space_key: str, user_key: str) -> None:
        """Grants space permissions to a user"""
        return self._put(GRANT_PERMISSIONS_TO_USER_1.path.format(spaceKey=space_key, userKey=user_key))

    def revoke_permissions_from_user_1(self, space_key: str, user_key: str) -> None:
        """Revoke space permissions from a user"""
        return self._put(REVOKE_PERMISSIONS_FROM_USER_1.path.format(spaceKey=space_key, userKey=user_key))


class SpacePropertyResource(ConfluenceResource):
    def get_1(
        self,
        space_key: str,
        *,
        expand: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[JsonSpaceProperty]:
        """Get space properties"""
        return self._get_paged(
            GET_1.path.format(spaceKey=space_key),
            params={"expand": expand},
            model=JsonSpaceProperty,
            start=start,
            limit=limit,
        )

    def create_3(self, space_key: str, body: JsonSpaceProperty) -> JsonSpaceProperty:
        """Create a space property"""
        return self._post(
            CREATE_3.path.format(spaceKey=space_key),
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=JsonSpaceProperty,
        )

    def delete_4(self, space_key: str, key: str) -> None:
        """Delete space property"""
        return self._delete(DELETE_4.path.format(spaceKey=space_key, key=key))

    def get(
        self,
        space_key: str,
        key: str,
        *,
        expand: str | None = None,
        limit: str | None = None,
        start: str | None = None,
    ) -> JsonSpaceProperty:
        """Get space property by key"""
        return self._get(
            GET.path.format(spaceKey=space_key, key=key),
            params={"expand": expand, "limit": limit, "start": start},
            model=JsonSpaceProperty,
        )

    def create_4(self, space_key: str, key: str, body: JsonSpaceProperty) -> JsonSpaceProperty:
        """Create a space property with a specific key"""
        return self._post(
            CREATE_4.path.format(spaceKey=space_key, key=key),
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=JsonSpaceProperty,
        )

    def update_3(self, space_key: str, key: str, body: JsonSpaceProperty) -> JsonSpaceProperty:
        """Update space property"""
        return self._put(
            UPDATE_3.path.format(spaceKey=space_key, key=key),
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=JsonSpaceProperty,
        )


class SpaceColorSchemeResource(ConfluenceResource):
    def get_space_color_scheme(self, space_key: str) -> ColorSchemeThemeBasedModel:
        """Get Space color scheme"""
        return self._get(GET_SPACE_COLOR_SCHEME.path.format(spaceKey=space_key), model=ColorSchemeThemeBasedModel)

    def update_space_color_scheme(
        self,
        space_key: str,
        body: ColorSchemeThemeBasedModel,
    ) -> ColorSchemeThemeBasedModel:
        """Update Space color scheme"""
        return self._put(
            UPDATE_SPACE_COLOR_SCHEME.path.format(spaceKey=space_key),
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=ColorSchemeThemeBasedModel,
        )

    def reset_space_color_scheme(self, space_key: str) -> ColorSchemeThemeBasedModel:
        """Reset Space color scheme"""
        return self._put(
            RESET_SPACE_COLOR_SCHEME.path.format(spaceKey=space_key),
            model=ColorSchemeThemeBasedModel,
        )

    def get_color_scheme_type(self, space_key: str) -> SpaceColorSchemeTypeModel:
        """Get Space color scheme type"""
        return self._get(GET_COLOR_SCHEME_TYPE.path.format(spaceKey=space_key), model=SpaceColorSchemeTypeModel)

    def update_color_scheme_type(
        self,
        space_key: str,
        body: SpaceColorSchemeTypeModel,
    ) -> SpaceColorSchemeTypeModel:
        """Update Space color scheme type"""
        return self._put(
            UPDATE_COLOR_SCHEME_TYPE.path.format(spaceKey=space_key),
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=SpaceColorSchemeTypeModel,
        )


class GroupResource(ConfluenceResource):
    def get_groups(self, *, expand: str | None = "", start: int = 0, limit: int = 25) -> PageIterator[Group]:
        """Get groups"""
        return self._get_paged(GET_GROUPS.path, params={"expand": expand}, model=Group, start=start, limit=limit)

    def get_group(self, group_name: str, *, expand: str | None = None) -> Group:
        """Get group by name"""
        return self._get(GET_GROUP.path.format(groupName=group_name), params={"expand": expand}, model=Group)

    def get_nested_group_members(
        self,
        group_name: Group,
        *,
        expand: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Group]:
        """Get group members of group"""
        return self._get_paged(
            GET_NESTED_GROUP_MEMBERS.path.format(groupName=group_name),
            params={"expand": expand},
            model=Group,
            start=start,
            limit=limit,
        )

    def get_members(
        self,
        group_name: Group,
        *,
        expand: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Person]:
        """Get members of group"""
        return self._get_paged(
            GET_MEMBERS.path.format(groupName=group_name),
            params={"expand": expand},
            model=Person,
            start=start,
            limit=limit,
        )

    def delete_6(self, group_name: str, username: str) -> None:
        """Delete user group"""
        return self._delete(DELETE_6.path.format(groupName=group_name, username=username))

    def update_5(self, group_name: str, username: str) -> None:
        """Update user group"""
        return self._put(UPDATE_5.path.format(groupName=group_name, username=username))


class UserResource(ConfluenceResource):
    def get_user(
        self,
        *,
        expand: str | None = None,
        key: str | None = None,
        username: str | None = None,
    ) -> Person:
        """Get user"""
        return self._get(GET_USER.path, params={"expand": expand, "key": key, "username": username}, model=Person)

    def get_anonymous(self, *, expand: str | None = None) -> Person:
        """Get information about anonymous user type"""
        return self._get(GET_ANONYMOUS.path, params={"expand": expand}, model=Person)

    def get_current(self, *, expand: str | None = None) -> Person:
        """Get current user"""
        return self._get(GET_CURRENT.path, params={"expand": expand}, model=Person)

    def update_user_1(self, body: UserDetailsForUpdate) -> None:
        """Update details of the current user"""
        return self._put(UPDATE_USER_1.path, json=body.model_dump(by_alias=True, exclude_none=True))

    def change_password_1(self, body: PasswordChangeDetails) -> None:
        """Change password"""
        return self._post(CHANGE_PASSWORD_1.path, json=body.model_dump(by_alias=True, exclude_none=True))

    def get_users(self, *, expand: str | None = None, start: int = 0, limit: int = 25) -> PageIterator[Person]:
        """Get registered users"""
        return self._get_paged(GET_USERS.path, params={"expand": expand}, model=Person, start=start, limit=limit)

    def get_groups_1(
        self,
        *,
        expand: str | None = None,
        key: str | None = None,
        username: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Person]:
        """Get groups"""
        return self._get_paged(
            GET_GROUPS_1.path,
            params={"expand": expand, "key": key, "username": username},
            model=Person,
            start=start,
            limit=limit,
        )


class UserWatchResource(ConfluenceResource):
    def remove_content_watcher(
        self,
        content_id: str,
        *,
        key: str | None = None,
        username: str | None = None,
    ) -> None:
        """Remove content watcher"""
        return self._delete(
            REMOVE_CONTENT_WATCHER.path.format(contentId=content_id),
            params={"key": key, "username": username},
        )

    def is_watching_content(
        self,
        content_id: str,
        *,
        key: str | None = None,
        username: str | None = None,
    ) -> None:
        """Get information about content watcher"""
        return self._get(
            IS_WATCHING_CONTENT.path.format(contentId=content_id),
            params={"key": key, "username": username},
        )

    def add_content_watcher(
        self,
        content_id: str,
        *,
        key: str | None = None,
        username: str | None = None,
    ) -> ContentWatch:
        """Add content watcher"""
        return self._post(
            ADD_CONTENT_WATCHER.path.format(contentId=content_id),
            params={"key": key, "username": username},
            model=ContentWatch,
        )

    def remove_space_watch(
        self,
        space_key: str,
        *,
        content_type: str | None = None,
        key: str | None = None,
        username: str | None = None,
    ) -> None:
        """Remove space watcher"""
        return self._delete(
            REMOVE_SPACE_WATCH.path.format(spaceKey=space_key),
            params={"contentType": content_type, "key": key, "username": username},
        )

    def is_watching_space(
        self,
        space_key: str,
        *,
        content_type: str | None = None,
        key: str | None = None,
        username: str | None = None,
    ) -> None:
        """Get information about space watcher"""
        return self._get(
            IS_WATCHING_SPACE.path.format(spaceKey=space_key),
            params={"contentType": content_type, "key": key, "username": username},
        )

    def add_space_watch(
        self,
        space_key: str,
        *,
        content_type: str | None = None,
        key: str | None = None,
        username: str | None = None,
    ) -> SpaceWatch:
        """Add space watcher"""
        return self._post(
            ADD_SPACE_WATCH.path.format(spaceKey=space_key),
            params={"contentType": content_type, "key": key, "username": username},
            model=SpaceWatch,
        )


class SearchResource(ConfluenceResource):
    def search_1(
        self,
        *,
        cqlcontext: str | None = None,
        expand: str | None = None,
        include_archived_spaces: str | None = None,
        excerpt: str | None = None,
        cql: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[SearchResult]:
        """Search for entities in confluence"""
        return self._get_paged(
            SEARCH_1.path,
            params={
                "cqlcontext": cqlcontext,
                "expand": expand,
                "includeArchivedSpaces": include_archived_spaces,
                "excerpt": excerpt,
                "cql": cql,
            },
            model=SearchResult,
            start=start,
            limit=limit,
        )


class LabelResource(ConfluenceResource):
    def labels_1(
        self,
        *,
        space_key: str | None = None,
        owner: str | None = None,
        namespace: str | None = None,
        label_name: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[Label]:
        """Get list of labels matching the given label name, namespace, space (via space key) or owner."""
        return self._get_paged(
            LABELS_1.path,
            params={"spaceKey": space_key, "owner": owner, "namespace": namespace, "labelName": label_name},
            model=Label,
            start=start,
            limit=limit,
        )

    def popular(self, *, start: int = 0, limit: int = 25) -> PageIterator[Label]:
        """Get most popular labels"""
        return self._get_paged(POPULAR.path, model=Label, start=start, limit=limit)

    def recent(self, *, start: int = 0, limit: int = 25) -> PageIterator[Label]:
        """Get recently used labels"""
        return self._get_paged(RECENT.path, model=Label, start=start, limit=limit)

    def related(self, label_name: str, *, start: int = 0, limit: int = 25) -> PageIterator[Label]:
        """Get related labels."""
        return self._get_paged(RELATED.path.format(labelName=label_name), model=Label, start=start, limit=limit)


class LongTaskResource(ConfluenceResource):
    def get_tasks(
        self,
        *,
        expand: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[LongTaskStatus]:
        """Get tasks"""
        return self._get_paged(
            GET_TASKS.path,
            params={"expand": expand},
            model=LongTaskStatus,
            start=start,
            limit=limit,
        )

    def get_task(self, id: str, *, expand: str | None = None) -> LongTaskStatus:
        """Get task by ID"""
        return self._get(GET_TASK.path.format(id=id), params={"expand": expand}, model=LongTaskStatus)


class BackupRestoreResource(ConfluenceResource):
    def create_site_backup_job(self, body: SiteBackupSettings) -> SiteBackupJobDetails:
        """Create site backup job"""
        return self._post(
            CREATE_SITE_BACKUP_JOB.path,
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=SiteBackupJobDetails,
        )

    def create_space_backup_job(self, body: SpaceBackupSettings) -> SpaceBackupJobDetails:
        """Create space backup job"""
        return self._post(
            CREATE_SPACE_BACKUP_JOB.path,
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=SpaceBackupJobDetails,
        )

    def find_jobs(
        self,
        *,
        owner: str | None = None,
        space_key: str | None = None,
        from_date: str | None = None,
        job_states: str | None = None,
        to_date: str | None = None,
        job_operation: str | None = None,
        limit: str | None = None,
        job_scope: str | None = None,
    ) -> JobDetails:
        """Find jobs by filters"""
        return self._get(
            FIND_JOBS.path,
            params={
                "owner": owner,
                "spaceKey": space_key,
                "fromDate": from_date,
                "jobStates": job_states,
                "toDate": to_date,
                "jobOperation": job_operation,
                "limit": limit,
                "jobScope": job_scope,
            },
            model=JobDetails,
        )

    def cancel_all_queued_jobs(self) -> None:
        """Cancel all queued jobs"""
        return self._put(CANCEL_ALL_QUEUED_JOBS.path)

    def get_job(self, job_id: str) -> JobDetails:
        """Get job by ID"""
        return self._get(GET_JOB.path.format(jobId=job_id), model=JobDetails)

    def cancel_job(self, job_id: str) -> JobDetails:
        """Cancel job"""
        return self._put(CANCEL_JOB.path.format(jobId=job_id), model=JobDetails)

    def download_backup_file(self, job_id: str) -> JobDetails:
        """Download backup file"""
        return self._get(DOWNLOAD_BACKUP_FILE.path.format(jobId=job_id), model=JobDetails)

    def get_files(self, *, job_scope: str | None = None) -> FileInfo:
        """Get files in restore directory"""
        return self._get(GET_FILES.path, params={"jobScope": job_scope}, model=FileInfo)

    def create_site_restore_job(self, body: SiteRestoreSettings) -> SiteRestoreJobDetails:
        """Create site restore job"""
        return self._post(
            CREATE_SITE_RESTORE_JOB.path,
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=SiteRestoreJobDetails,
        )

    def create_site_restore_job_for_uploaded_backup_file(
        self,
        body: ExampleMultipartFormData,
    ) -> SiteRestoreJobDetails:
        """Create site restore job for upload backup file"""
        return self._post(
            CREATE_SITE_RESTORE_JOB_FOR_UPLOADED_BACKUP_FILE.path,
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=SiteRestoreJobDetails,
        )

    def create_space_restore_job(self, body: SpaceRestoreSettings) -> SpaceRestoreJobDetails:
        """Create space restore job"""
        return self._post(
            CREATE_SPACE_RESTORE_JOB.path,
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=SpaceRestoreJobDetails,
        )

    def create_space_restore_job_for_uploaded_backup_file(
        self,
        body: ExampleMultipartFormData,
    ) -> SpaceRestoreJobDetails:
        """Create space restore job for upload backup file"""
        return self._post(
            CREATE_SPACE_RESTORE_JOB_FOR_UPLOADED_BACKUP_FILE.path,
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=SpaceRestoreJobDetails,
        )


class WebhooksResource(ConfluenceResource):
    def find_webhooks(
        self,
        *,
        event: str | None = None,
        statistics: str | None = None,
        start: int = 0,
        limit: int = 25,
    ) -> PageIterator[RestWebhook]:
        """Find webhooks"""
        return self._get_paged(
            FIND_WEBHOOKS.path,
            params={"event": event, "statistics": statistics},
            model=RestWebhook,
            start=start,
            limit=limit,
        )

    def create_webhook(self, body: RestWebhook) -> Webhook:
        """Create webhook"""
        return self._post(
            CREATE_WEBHOOK.path,
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=Webhook,
        )

    def test_webhook(self, *, url: str) -> None:
        """Test webhook"""
        return self._post(TEST_WEBHOOK.path, params={"url": url})

    def delete_webhook(self, webhook_id: str) -> None:
        """Delete webhook"""
        return self._delete(DELETE_WEBHOOK.path.format(webhookId=webhook_id))

    def get_webhook(self, webhook_id: str, *, statistics: bool | None = False) -> RestWebhook:
        """Get webhook"""
        return self._get(
            GET_WEBHOOK.path.format(webhookId=webhook_id),
            params={"statistics": statistics},
            model=RestWebhook,
        )

    def update_webhook(self, webhook_id: str, body: RestWebhook) -> RestWebhook:
        """Update webhook"""
        return self._put(
            UPDATE_WEBHOOK.path.format(webhookId=webhook_id),
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=RestWebhook,
        )

    def get_latest_invocation(
        self,
        webhook_id: str,
        *,
        outcomes: str | None = None,
        event: str | None = None,
        outcome: list[str] | None = None,
    ) -> DetailedInvocation:
        """Get latest invocations"""
        return self._get(
            GET_LATEST_INVOCATION.path.format(webhookId=webhook_id),
            params={"outcomes": outcomes, "event": event, "outcome": outcome},
            model=DetailedInvocation,
        )

    def get_statistics(self, webhook_id: str, *, event: str | None = None) -> RestInvocationHistory:
        """Get statistic"""
        return self._get(
            GET_STATISTICS.path.format(webhookId=webhook_id),
            params={"event": event},
            model=RestInvocationHistory,
        )

    def get_statistics_summary(self, webhook_id: str) -> RestInvocationHistory:
        """Get statistics summary"""
        return self._get(GET_STATISTICS_SUMMARY.path.format(webhookId=webhook_id), model=RestInvocationHistory)


class GlobalPermissionsResource(ConfluenceResource):
    def get_all_global_permissions(self) -> GlobalPermission:
        """Get global permissions"""
        return self._get(GET_ALL_GLOBAL_PERMISSIONS.path, model=GlobalPermission)

    def set_permissions(self) -> None:
        """Set global permissions to multiple users/groups"""
        return self._put(SET_PERMISSIONS.path)

    def get_permissions_granted_to_anonymous_users(self) -> GlobalPermission:
        """Gets the permissions granted to an anonymous user"""
        return self._get(GET_PERMISSIONS_GRANTED_TO_ANONYMOUS_USERS.path, model=GlobalPermission)

    def grant_permissions_to_anonymous_users(self) -> None:
        """Grants global permissions to anonymous users"""
        return self._put(GRANT_PERMISSIONS_TO_ANONYMOUS_USERS.path)

    def revoke_permissions_from_anonymous_users(self) -> None:
        """Revoke global permissions from anonymous users"""
        return self._put(REVOKE_PERMISSIONS_FROM_ANONYMOUS_USERS.path)

    def get_permissions_granted_to_group(self, group_name: str) -> GlobalPermission:
        """Gets global permissions granted to a group"""
        return self._get(
            GET_PERMISSIONS_GRANTED_TO_GROUP.path.format(groupName=group_name),
            model=GlobalPermission,
        )

    def grant_permissions_to_group(self, group_name: str) -> None:
        """Grants global permissions to a group"""
        return self._put(GRANT_PERMISSIONS_TO_GROUP.path.format(groupName=group_name))

    def revoke_permissions_from_group(self, group_name: str) -> None:
        """Revoke global permissions from a group"""
        return self._put(REVOKE_PERMISSIONS_FROM_GROUP.path.format(groupName=group_name))

    def get_permissions_granted_to_unlicensed_users(self) -> GlobalPermission:
        """Gets the permissions granted to an unlicensed users"""
        return self._get(GET_PERMISSIONS_GRANTED_TO_UNLICENSED_USERS.path, model=GlobalPermission)

    def grant_permissions_to_unlicensed_users(self) -> None:
        """Grants global permissions to unlicensed users"""
        return self._put(GRANT_PERMISSIONS_TO_UNLICENSED_USERS.path)

    def revoke_permissions_from_unlicensed_users(self) -> None:
        """Revoke global permissions from unlicensed users"""
        return self._put(REVOKE_PERMISSIONS_FROM_UNLICENSED_USERS.path)

    def get_permissions_granted_to_user(self, user: str) -> GlobalPermission:
        """Gets global permissions granted to a user"""
        return self._get(GET_PERMISSIONS_GRANTED_TO_USER.path.format(user=user), model=GlobalPermission)

    def grant_permissions_to_user(self, user: str) -> None:
        """Grants global permissions to a user"""
        return self._put(GRANT_PERMISSIONS_TO_USER.path.format(user=user))

    def revoke_permissions_from_user(self, user: str) -> None:
        """Revoke global permissions from a user"""
        return self._put(REVOKE_PERMISSIONS_FROM_USER.path.format(user=user))


class GlobalColorSchemeResource(ConfluenceResource):
    def get_global_color_scheme(self) -> ColorSchemeThemeBasedModel:
        """Get global color scheme"""
        return self._get(GET_GLOBAL_COLOR_SCHEME.path, model=ColorSchemeThemeBasedModel)

    def update_color_scheme(self, body: ColorSchemeThemeBasedModel) -> ColorSchemeThemeBasedModel:
        """Set global color scheme"""
        return self._put(
            UPDATE_COLOR_SCHEME.path,
            json=body.model_dump(by_alias=True, exclude_none=True),
            model=ColorSchemeThemeBasedModel,
        )

    def get_default_color_scheme(self) -> ColorSchemeThemeBasedModel:
        """Get default global color scheme"""
        return self._get(GET_DEFAULT_COLOR_SCHEME.path, model=ColorSchemeThemeBasedModel)

    def reset_global_color_scheme(self) -> ColorSchemeThemeBasedModel:
        """Reset global color scheme"""
        return self._put(RESET_GLOBAL_COLOR_SCHEME.path, model=ColorSchemeThemeBasedModel)


class CategoryResource(ConfluenceResource):
    def remove_category(self, space_key: str, category_name: str) -> None:
        """Remove a category from a space"""
        return self._delete(REMOVE_CATEGORY.path.format(spaceKey=space_key, categoryName=category_name))

    def add(self, space_key: str, label_name: str) -> None:
        """Add a category to a space"""
        return self._post(ADD.path.format(spaceKey=space_key, labelName=label_name))


class AccessModeResource(ConfluenceResource):
    def get_access_mode_status(self) -> None:
        """Get access mode status"""
        return self._get(GET_ACCESS_MODE_STATUS.path)


class ServerInfoResource(ConfluenceResource):
    def index_1(self) -> InstanceMetrics:
        """Get instance metrics"""
        return self._get(INDEX_1.path, model=InstanceMetrics)

    def index_2(self) -> ServerInformation:
        """Get server information"""
        return self._get(INDEX_2.path, model=ServerInformation)


class AdminResource(ConfluenceResource):
    def create(self, body: Group) -> Group:
        """Create group"""
        return self._post(CREATE.path, json=body.model_dump(by_alias=True, exclude_none=True), model=Group)

    def delete(self, group_name: str) -> None:
        """Delete group"""
        return self._delete(DELETE.path.format(groupName=group_name))

    def create_user(self, body: UserDetailsForCreation) -> UserKey:
        """Create user"""
        return self._post(CREATE_USER.path, json=body.model_dump(by_alias=True, exclude_none=True), model=UserKey)

    def delete_1(self, username: str) -> LongTaskSubmission:
        """Delete user"""
        return self._delete(DELETE_1.path.format(username=username), model=LongTaskSubmission)

    def update_user(self, username: str, body: UserDetailsForUpdate) -> None:
        """Update user"""
        return self._put(
            UPDATE_USER.path.format(username=username),
            json=body.model_dump(by_alias=True, exclude_none=True),
        )

    def disable(self, username: str) -> None:
        """Disable user"""
        return self._put(DISABLE.path.format(username=username))

    def enable(self, username: str) -> None:
        """Enable user"""
        return self._put(ENABLE.path.format(username=username))

    def change_password(self, username: str, body: Credentials) -> None:
        """Change password"""
        return self._post(
            CHANGE_PASSWORD.path.format(username=username),
            json=body.model_dump(by_alias=True, exclude_none=True),
        )

    def get_audit_records(self) -> None:
        """GET /rest/api/audit"""
        return self._get(GET_AUDIT_RECORDS.path)
